"""Bilingual question bank for O Level quiz (English + Hindi).

Each question schema:
  q_en, q_hi, options_en, options_hi, a (correct index), exp_en, exp_hi
"""

M1 = [
    {"q_en": "What is the full form of COMPUTER?", "q_hi": "COMPUTER का पूर्ण रूप क्या है?",
     "options_en": ["Common Operating Machine Purposely Used for Technological and Educational Research", "Common Object Machine Used in Technical Electronic Research", "Central Operating Machine for Tech Education Research", "None of these"],
     "options_hi": ["कॉमन ऑपरेटिंग मशीन पर्पजली यूज्ड फॉर टेक्नोलॉजिकल एंड एजुकेशनल रिसर्च", "कॉमन ऑब्जेक्ट मशीन यूज्ड इन टेक्निकल इलेक्ट्रॉनिक रिसर्च", "सेंट्रल ऑपरेटिंग मशीन फॉर टेक एजुकेशन रिसर्च", "इनमें से कोई नहीं"],
     "a": 0, "exp_en": "COMPUTER stands for Common Operating Machine Purposely Used for Technological and Educational Research.", "exp_hi": "COMPUTER का अर्थ है Common Operating Machine Purposely Used for Technological and Educational Research।"},
    {"q_en": "Which of the following is an input device?", "q_hi": "निम्न में से कौन-सा इनपुट उपकरण है?",
     "options_en": ["Monitor", "Keyboard", "Printer", "Speaker"], "options_hi": ["मॉनिटर", "कीबोर्ड", "प्रिंटर", "स्पीकर"],
     "a": 1, "exp_en": "Keyboard is used to input data; the others are output devices.", "exp_hi": "कीबोर्ड डेटा इनपुट करने के लिए होता है; अन्य आउटपुट उपकरण हैं।"},
    {"q_en": "1 KB is equal to how many bytes?", "q_hi": "1 KB कितने बाइट के बराबर होता है?",
     "options_en": ["1000", "1024", "100", "512"], "options_hi": ["1000", "1024", "100", "512"],
     "a": 1, "exp_en": "1 KB = 1024 bytes in binary system.", "exp_hi": "बाइनरी पद्धति में 1 KB = 1024 बाइट।"},
    {"q_en": "Which of these is volatile memory?", "q_hi": "इनमें से कौन-सी वोलेटाइल मेमोरी है?",
     "options_en": ["ROM", "Hard Disk", "RAM", "Flash Drive"], "options_hi": ["ROM", "हार्ड डिस्क", "RAM", "फ्लैश ड्राइव"],
     "a": 2, "exp_en": "RAM is volatile — data is lost when power goes off.", "exp_hi": "RAM वोलेटाइल है — बिजली जाने पर डेटा मिट जाता है।"},
    {"q_en": "What is the default extension of an MS Word 2010+ file?", "q_hi": "MS Word 2010+ फाइल का डिफ़ॉल्ट एक्सटेंशन क्या है?",
     "options_en": [".doc", ".docx", ".txt", ".pdf"], "options_hi": [".doc", ".docx", ".txt", ".pdf"],
     "a": 1, "exp_en": "Office 2007 onwards uses .docx as default.", "exp_hi": "Office 2007 से Word में .docx डिफ़ॉल्ट है।"},
    {"q_en": "Ctrl + C shortcut is used for?", "q_hi": "Ctrl + C शॉर्टकट किसके लिए प्रयोग होता है?",
     "options_en": ["Cut", "Copy", "Paste", "Close"], "options_hi": ["कट", "कॉपी", "पेस्ट", "बंद करना"],
     "a": 1, "exp_en": "Ctrl+C copies selected content to clipboard.", "exp_hi": "Ctrl+C चयनित सामग्री को क्लिपबोर्ड पर कॉपी करता है।"},
    {"q_en": "Which device connects a computer to the internet?", "q_hi": "कौन-सा उपकरण कंप्यूटर को इंटरनेट से जोड़ता है?",
     "options_en": ["Router", "Modem", "Switch", "Hub"], "options_hi": ["राउटर", "मॉडेम", "स्विच", "हब"],
     "a": 1, "exp_en": "Modem connects to ISP to access the internet.", "exp_hi": "मॉडेम ISP से जुड़कर इंटरनेट उपलब्ध कराता है।"},
    {"q_en": "What is the primary function of an operating system?", "q_hi": "ऑपरेटिंग सिस्टम का मुख्य कार्य क्या है?",
     "options_en": ["Manage hardware and software resources", "Edit documents", "Browse internet", "Play music"], "options_hi": ["हार्डवेयर और सॉफ्टवेयर संसाधनों का प्रबंधन", "दस्तावेज़ संपादित करना", "इंटरनेट चलाना", "संगीत चलाना"],
     "a": 0, "exp_en": "OS manages all hardware and software resources.", "exp_hi": "OS कंप्यूटर के सभी संसाधनों का प्रबंधन करता है।"},
    {"q_en": "Which of these is NOT an operating system?", "q_hi": "इनमें से कौन-सा ऑपरेटिंग सिस्टम नहीं है?",
     "options_en": ["Windows", "Linux", "Oracle", "macOS"], "options_hi": ["विंडोज़", "लिनक्स", "ओरेकल", "मैकओएस"],
     "a": 2, "exp_en": "Oracle is a database system, not an OS.", "exp_hi": "ओरेकल डेटाबेस है, OS नहीं।"},
    {"q_en": "Binary number system uses which digits?", "q_hi": "बाइनरी संख्या पद्धति में कौन-से अंक होते हैं?",
     "options_en": ["0-9", "0 and 1", "0-7", "A-F"], "options_hi": ["0-9", "0 और 1", "0-7", "A-F"],
     "a": 1, "exp_en": "Binary uses only 0 and 1.", "exp_hi": "बाइनरी में केवल 0 और 1 प्रयोग होते हैं।"},
    {"q_en": "CPU stands for?", "q_hi": "CPU का पूर्ण रूप क्या है?",
     "options_en": ["Central Processing Unit", "Computer Personal Unit", "Central Process Utility", "Control Program Unit"], "options_hi": ["सेंट्रल प्रोसेसिंग यूनिट", "कंप्यूटर पर्सनल यूनिट", "सेंट्रल प्रोसेस यूटिलिटी", "कंट्रोल प्रोग्राम यूनिट"],
     "a": 0, "exp_en": "CPU = Central Processing Unit, the brain of a computer.", "exp_hi": "CPU कंप्यूटर का मस्तिष्क है।"},
    {"q_en": "Which key deletes the character to the left of the cursor?", "q_hi": "कौन-सी की कर्सर की बाईं ओर का अक्षर मिटाती है?",
     "options_en": ["Delete", "Backspace", "Shift", "Enter"], "options_hi": ["डिलीट", "बैकस्पेस", "शिफ्ट", "एंटर"],
     "a": 1, "exp_en": "Backspace deletes character on the left of the cursor.", "exp_hi": "बैकस्पेस बाईं ओर का अक्षर मिटाती है।"},
    {"q_en": "How many bits are in one byte?", "q_hi": "एक बाइट में कितने बिट होते हैं?",
     "options_en": ["4", "8", "16", "32"], "options_hi": ["4", "8", "16", "32"],
     "a": 1, "exp_en": "1 byte = 8 bits.", "exp_hi": "1 बाइट = 8 बिट।"},
    {"q_en": "Which of the following is system software?", "q_hi": "इनमें से कौन-सा सिस्टम सॉफ्टवेयर है?",
     "options_en": ["MS Word", "Photoshop", "Windows 10", "VLC Player"], "options_hi": ["एम.एस. वर्ड", "फोटोशॉप", "विंडोज़ 10", "वी.एल.सी. प्लेयर"],
     "a": 2, "exp_en": "Windows 10 is an operating system (system software).", "exp_hi": "विंडोज़ 10 एक ऑपरेटिंग सिस्टम है।"},
    {"q_en": "What is the extension of an Excel file?", "q_hi": "एक्सेल फाइल का एक्सटेंशन क्या होता है?",
     "options_en": [".xls/.xlsx", ".doc", ".ppt", ".txt"], "options_hi": [".xls/.xlsx", ".doc", ".ppt", ".txt"],
     "a": 0, "exp_en": "Excel files use .xls or .xlsx.", "exp_hi": "एक्सेल फाइलें .xls या .xlsx होती हैं।"},
    {"q_en": "Who invented the World Wide Web?", "q_hi": "वर्ल्ड वाइड वेब का आविष्कार किसने किया?",
     "options_en": ["Bill Gates", "Tim Berners-Lee", "Steve Jobs", "Larry Page"], "options_hi": ["बिल गेट्स", "टिम बर्नर्स-ली", "स्टीव जॉब्स", "लैरी पेज"],
     "a": 1, "exp_en": "Tim Berners-Lee invented WWW in 1989.", "exp_hi": "टिम बर्नर्स-ली ने 1989 में WWW का आविष्कार किया।"},
    {"q_en": "Which shortcut refreshes a webpage?", "q_hi": "कौन-सा शॉर्टकट वेबपेज रिफ्रेश करता है?",
     "options_en": ["Ctrl+R / F5", "Ctrl+F", "Alt+F4", "Ctrl+Z"], "options_hi": ["Ctrl+R / F5", "Ctrl+F", "Alt+F4", "Ctrl+Z"],
     "a": 0, "exp_en": "F5 or Ctrl+R refreshes the page.", "exp_hi": "F5 या Ctrl+R पेज रिफ्रेश करता है।"},
    {"q_en": "In HTTPS, what does 'S' stand for?", "q_hi": "HTTPS में 'S' का अर्थ क्या है?",
     "options_en": ["Simple", "Secure", "Strong", "Smart"], "options_hi": ["सरल", "सुरक्षित", "मजबूत", "स्मार्ट"],
     "a": 1, "exp_en": "HTTPS = HyperText Transfer Protocol Secure.", "exp_hi": "HTTPS यानी सुरक्षित HTTP।"},
    {"q_en": "Which of these stores data permanently?", "q_hi": "इनमें से कौन डेटा को स्थायी रूप से रखता है?",
     "options_en": ["RAM", "Cache", "Hard Disk", "Register"], "options_hi": ["RAM", "कैश", "हार्ड डिस्क", "रजिस्टर"],
     "a": 2, "exp_en": "Hard Disk is non-volatile and stores data permanently.", "exp_hi": "हार्ड डिस्क नॉन-वोलेटाइल है, डेटा स्थायी रहता है।"},
    {"q_en": "GUI stands for?", "q_hi": "GUI का पूर्ण रूप क्या है?",
     "options_en": ["Graphic User Interface", "Graphical User Interface", "General User Interface", "Geographical Unit Interface"], "options_hi": ["ग्राफिक यूज़र इंटरफ़ेस", "ग्राफिकल यूज़र इंटरफ़ेस", "जनरल यूज़र इंटरफ़ेस", "जियोग्राफिकल यूनिट इंटरफ़ेस"],
     "a": 1, "exp_en": "GUI = Graphical User Interface.", "exp_hi": "GUI यानी ग्राफिकल यूज़र इंटरफ़ेस।"},
    {"q_en": "Which MS Word tab contains the 'Font' group?", "q_hi": "MS Word के किस टैब में 'Font' समूह होता है?",
     "options_en": ["Home", "Insert", "Review", "View"], "options_hi": ["होम", "इन्सर्ट", "रिव्यू", "व्यू"],
     "a": 0, "exp_en": "Home tab contains font formatting options.", "exp_hi": "होम टैब में फॉन्ट विकल्प होते हैं।"},
    {"q_en": "What does LAN stand for?", "q_hi": "LAN का पूर्ण रूप क्या है?",
     "options_en": ["Local Area Network", "Large Area Network", "Link Access Network", "Long Area Network"], "options_hi": ["लोकल एरिया नेटवर्क", "लार्ज एरिया नेटवर्क", "लिंक एक्सेस नेटवर्क", "लॉन्ग एरिया नेटवर्क"],
     "a": 0, "exp_en": "LAN = Local Area Network.", "exp_hi": "LAN यानी लोकल एरिया नेटवर्क।"},
    {"q_en": "Which printer is faster and quieter?", "q_hi": "कौन-सा प्रिंटर तेज़ और शांत होता है?",
     "options_en": ["Dot Matrix", "Laser", "Inkjet", "Daisy Wheel"], "options_hi": ["डॉट मैट्रिक्स", "लेज़र", "इंकजेट", "डेज़ी व्हील"],
     "a": 1, "exp_en": "Laser printers are fast, quiet and high-quality.", "exp_hi": "लेज़र प्रिंटर तेज़, शांत और अच्छी क्वालिटी वाले होते हैं।"},
    {"q_en": "Which is an example of cloud storage?", "q_hi": "क्लाउड स्टोरेज का उदाहरण कौन-सा है?",
     "options_en": ["Notepad", "Google Drive", "MS Paint", "Calculator"], "options_hi": ["नोटपैड", "गूगल ड्राइव", "एम.एस. पेंट", "कैलकुलेटर"],
     "a": 1, "exp_en": "Google Drive is a cloud storage service.", "exp_hi": "गूगल ड्राइव क्लाउड स्टोरेज सेवा है।"},
    {"q_en": "What is the main role of an antivirus?", "q_hi": "एंटीवायरस का मुख्य कार्य क्या है?",
     "options_en": ["Create viruses", "Detect and remove malware", "Speed up internet", "Edit photos"], "options_hi": ["वायरस बनाना", "मैलवेयर पहचानना और हटाना", "इंटरनेट तेज़ करना", "फोटो संपादित करना"],
     "a": 1, "exp_en": "Antivirus detects and removes viruses / malware.", "exp_hi": "एंटीवायरस वायरस पहचानता और हटाता है।"},
    {"q_en": "1 Gigabyte equals approximately how many Megabytes?", "q_hi": "1 गीगाबाइट लगभग कितने मेगाबाइट के बराबर होता है?",
     "options_en": ["512", "1024", "100", "2048"], "options_hi": ["512", "1024", "100", "2048"],
     "a": 1, "exp_en": "1 GB = 1024 MB.", "exp_hi": "1 GB = 1024 MB।"},
    {"q_en": "Which of the following is an output device?", "q_hi": "इनमें से कौन-सा आउटपुट उपकरण है?",
     "options_en": ["Scanner", "Microphone", "Monitor", "Mouse"], "options_hi": ["स्कैनर", "माइक्रोफोन", "मॉनिटर", "माउस"],
     "a": 2, "exp_en": "Monitor displays output to the user.", "exp_hi": "मॉनिटर आउटपुट दिखाता है।"},
    {"q_en": "What does URL stand for?", "q_hi": "URL का पूर्ण रूप क्या है?",
     "options_en": ["Uniform Resource Locator", "Universal Resource Link", "Uniform Reference Locator", "Unified Resource Line"], "options_hi": ["यूनिफॉर्म रिसोर्स लोकेटर", "यूनिवर्सल रिसोर्स लिंक", "यूनिफॉर्म रेफरेंस लोकेटर", "यूनिफाइड रिसोर्स लाइन"],
     "a": 0, "exp_en": "URL = Uniform Resource Locator — address of a web resource.", "exp_hi": "URL यानी किसी वेब संसाधन का पता।"},
    {"q_en": "Which key combination saves a document in MS Office?", "q_hi": "MS Office में दस्तावेज़ सहेजने की कुंजी क्या है?",
     "options_en": ["Ctrl+S", "Ctrl+P", "Ctrl+N", "Ctrl+O"], "options_hi": ["Ctrl+S", "Ctrl+P", "Ctrl+N", "Ctrl+O"],
     "a": 0, "exp_en": "Ctrl+S saves the current document.", "exp_hi": "Ctrl+S दस्तावेज़ सहेजता है।"},
    {"q_en": "A cell in Excel is identified by?", "q_hi": "एक्सेल में एक सेल की पहचान किससे होती है?",
     "options_en": ["Row only", "Column only", "Column letter + Row number", "Sheet name only"], "options_hi": ["केवल पंक्ति", "केवल स्तंभ", "स्तंभ अक्षर + पंक्ति संख्या", "केवल शीट नाम"],
     "a": 2, "exp_en": "Cell reference is e.g. A1, B5 (column letter + row number).", "exp_hi": "जैसे A1, B5 — स्तंभ अक्षर और पंक्ति संख्या।"},
    {"q_en": "Which PowerPoint view is used to add speaker notes?", "q_hi": "स्पीकर नोट्स जोड़ने के लिए PowerPoint का कौन-सा व्यू होता है?",
     "options_en": ["Slide Show", "Normal", "Reading", "Outline"], "options_hi": ["स्लाइड शो", "नॉर्मल", "रीडिंग", "आउटलाइन"],
     "a": 1, "exp_en": "Normal view has a notes pane under each slide.", "exp_hi": "नॉर्मल व्यू में स्लाइड के नीचे नोट्स लिखे जाते हैं।"},
    {"q_en": "The smallest unit of data in a computer is?", "q_hi": "कंप्यूटर में डेटा की सबसे छोटी इकाई क्या है?",
     "options_en": ["Byte", "Bit", "Nibble", "Word"], "options_hi": ["बाइट", "बिट", "निबल", "वर्ड"],
     "a": 1, "exp_en": "A bit (0 or 1) is the smallest data unit.", "exp_hi": "बिट (0 या 1) सबसे छोटी इकाई है।"},
    {"q_en": "Which memory is closest to the CPU and fastest?", "q_hi": "CPU के सबसे पास और सबसे तेज़ मेमोरी कौन-सी है?",
     "options_en": ["Hard Disk", "RAM", "Cache", "DVD"], "options_hi": ["हार्ड डिस्क", "RAM", "कैश", "DVD"],
     "a": 2, "exp_en": "Cache memory is closest to and fastest for the CPU.", "exp_hi": "कैश मेमोरी CPU के सबसे पास और तेज़ है।"},
    {"q_en": "Which of these is a web browser?", "q_hi": "इनमें से कौन-सा वेब ब्राउज़र है?",
     "options_en": ["Gmail", "Outlook", "Chrome", "Yahoo"], "options_hi": ["जीमेल", "आउटलुक", "क्रोम", "याहू"],
     "a": 2, "exp_en": "Google Chrome is a web browser.", "exp_hi": "गूगल क्रोम एक वेब ब्राउज़र है।"},
    {"q_en": "Which protocol is used to send email?", "q_hi": "ईमेल भेजने के लिए कौन-सा प्रोटोकॉल होता है?",
     "options_en": ["SMTP", "HTTP", "FTP", "DNS"], "options_hi": ["SMTP", "HTTP", "FTP", "DNS"],
     "a": 0, "exp_en": "SMTP (Simple Mail Transfer Protocol) is used to send email.", "exp_hi": "SMTP से ईमेल भेजा जाता है।"},
    {"q_en": "What is firmware?", "q_hi": "फर्मवेयर क्या है?",
     "options_en": ["Hardware device", "Software stored in hardware (ROM)", "A virus", "Cloud app"], "options_hi": ["हार्डवेयर उपकरण", "हार्डवेयर (ROM) में संग्रहीत सॉफ्टवेयर", "एक वायरस", "क्लाउड एप"],
     "a": 1, "exp_en": "Firmware is low-level software embedded in ROM/flash of a device.", "exp_hi": "फर्मवेयर डिवाइस के ROM में मौजूद लो-लेवल सॉफ्टवेयर है।"},
    {"q_en": "Which is the largest unit among the following?", "q_hi": "निम्न में से सबसे बड़ी इकाई कौन-सी है?",
     "options_en": ["KB", "MB", "GB", "TB"], "options_hi": ["KB", "MB", "GB", "TB"],
     "a": 3, "exp_en": "TB (Terabyte) is the largest here.", "exp_hi": "TB सबसे बड़ी इकाई है।"},
    {"q_en": "Which key is used to capitalize letters temporarily?", "q_hi": "अक्षरों को कुछ देर कैपिटल करने के लिए कौन-सी कुंजी प्रयोग होती है?",
     "options_en": ["Caps Lock", "Shift", "Ctrl", "Alt"], "options_hi": ["कैप्स लॉक", "शिफ्ट", "कंट्रोल", "ऑल्ट"],
     "a": 1, "exp_en": "Shift + letter gives capital letter temporarily.", "exp_hi": "शिफ्ट दबाकर अक्षर कैपिटल मिलता है।"},
    {"q_en": "What is the main function of the ALU?", "q_hi": "ALU का मुख्य कार्य क्या है?",
     "options_en": ["Store data", "Perform arithmetic and logical operations", "Display output", "Input data"], "options_hi": ["डेटा संग्रह करना", "अंकगणितीय और तार्किक क्रियाएँ करना", "आउटपुट दिखाना", "डेटा इनपुट करना"],
     "a": 1, "exp_en": "ALU (Arithmetic Logic Unit) performs arithmetic and logical operations.", "exp_hi": "ALU अंकगणित और लॉजिक की गणनाएँ करता है।"},
    {"q_en": "An IP address is?", "q_hi": "IP पता क्या है?",
     "options_en": ["Name of a computer", "Unique number identifying a device on a network", "An email ID", "A program"], "options_hi": ["कंप्यूटर का नाम", "नेटवर्क पर उपकरण की विशिष्ट पहचान संख्या", "एक ईमेल आईडी", "एक प्रोग्राम"],
     "a": 1, "exp_en": "IP address uniquely identifies a device on a network.", "exp_hi": "IP पता नेटवर्क पर उपकरण को विशिष्ट रूप से पहचानता है।"},
    {"q_en": "Which Excel function finds the total of a range?", "q_hi": "एक्सेल में किसी रेंज का कुल जोड़ कौन-सा फ़ंक्शन करता है?",
     "options_en": ["AVERAGE", "SUM", "COUNT", "MAX"], "options_hi": ["AVERAGE", "SUM", "COUNT", "MAX"],
     "a": 1, "exp_en": "SUM adds up a range of values.", "exp_hi": "SUM फ़ंक्शन मानों का योग करता है।"},
    {"q_en": "Which of these is NOT an example of a web browser?", "q_hi": "इनमें से कौन वेब ब्राउज़र नहीं है?",
     "options_en": ["Firefox", "Safari", "Edge", "Linux"], "options_hi": ["फ़ायरफ़ॉक्स", "सफारी", "एज", "लिनक्स"],
     "a": 3, "exp_en": "Linux is an OS, not a browser.", "exp_hi": "लिनक्स एक OS है, ब्राउज़र नहीं।"},
    {"q_en": "A firewall is used to?", "q_hi": "फ़ायरवॉल का उपयोग किसलिए होता है?",
     "options_en": ["Cool the computer", "Block unauthorized network access", "Store files", "Edit documents"], "options_hi": ["कंप्यूटर ठंडा करना", "अनधिकृत नेटवर्क पहुँच रोकना", "फ़ाइलें सहेजना", "दस्तावेज़ बदलना"],
     "a": 1, "exp_en": "Firewall controls and blocks unauthorized network traffic.", "exp_hi": "फ़ायरवॉल अनधिकृत नेटवर्क पहुँच को रोकता है।"},
    {"q_en": "Which of the following is an open-source OS?", "q_hi": "इनमें से कौन-सा ओपन सोर्स OS है?",
     "options_en": ["Windows", "macOS", "Linux", "iOS"], "options_hi": ["विंडोज़", "मैकओएस", "लिनक्स", "आईओएस"],
     "a": 2, "exp_en": "Linux is free and open-source.", "exp_hi": "लिनक्स मुफ्त और ओपन सोर्स है।"},
    {"q_en": "Which shortcut selects all content in a document?", "q_hi": "दस्तावेज़ की सारी सामग्री चुनने की कुंजी क्या है?",
     "options_en": ["Ctrl+A", "Ctrl+S", "Ctrl+X", "Ctrl+V"], "options_hi": ["Ctrl+A", "Ctrl+S", "Ctrl+X", "Ctrl+V"],
     "a": 0, "exp_en": "Ctrl+A selects all.", "exp_hi": "Ctrl+A सारा चयन कर देता है।"},
    {"q_en": "In a spreadsheet, a formula always starts with?", "q_hi": "स्प्रेडशीट में सूत्र हमेशा किससे शुरू होता है?",
     "options_en": ["=", "+", "-", "*"], "options_hi": ["=", "+", "-", "*"],
     "a": 0, "exp_en": "Excel formulas begin with '='.", "exp_hi": "एक्सेल सूत्र '=' से शुरू होते हैं।"},
    {"q_en": "Which type of software is MS Paint?", "q_hi": "MS Paint किस प्रकार का सॉफ्टवेयर है?",
     "options_en": ["System software", "Utility", "Application software", "Firmware"], "options_hi": ["सिस्टम सॉफ्टवेयर", "यूटिलिटी", "एप्लिकेशन सॉफ्टवेयर", "फर्मवेयर"],
     "a": 2, "exp_en": "MS Paint is an application software used for drawing.", "exp_hi": "MS Paint एक एप्लिकेशन सॉफ्टवेयर है।"},
    {"q_en": "Which device works as both input and output?", "q_hi": "कौन-सा उपकरण इनपुट और आउटपुट दोनों का काम करता है?",
     "options_en": ["Mouse", "Touchscreen", "Speaker", "Keyboard"], "options_hi": ["माउस", "टचस्क्रीन", "स्पीकर", "कीबोर्ड"],
     "a": 1, "exp_en": "Touchscreen accepts input and displays output.", "exp_hi": "टचस्क्रीन इनपुट भी लेता है और आउटपुट भी दिखाता है।"},
    {"q_en": "What does DNS stand for?", "q_hi": "DNS का पूर्ण रूप क्या है?",
     "options_en": ["Domain Name System", "Direct Network Service", "Data Name Server", "Dynamic Naming Service"], "options_hi": ["डोमेन नेम सिस्टम", "डायरेक्ट नेटवर्क सर्विस", "डेटा नेम सर्वर", "डायनेमिक नेमिंग सर्विस"],
     "a": 0, "exp_en": "DNS = Domain Name System — converts names to IP addresses.", "exp_hi": "DNS डोमेन नाम को IP पते में बदलता है।"},
]

M2 = [
    {"q_en": "What is the full form of HTML?", "q_hi": "HTML का पूर्ण रूप क्या है?",
     "options_en": ["Hyper Text Markup Language", "High Text Machine Language", "Hyper Tabular Markup Language", "None"], "options_hi": ["हाइपर टेक्स्ट मार्कअप लैंग्वेज", "हाई टेक्स्ट मशीन लैंग्वेज", "हाइपर टैब्युलर मार्कअप लैंग्वेज", "इनमें से कोई नहीं"],
     "a": 0, "exp_en": "HTML = HyperText Markup Language.", "exp_hi": "HTML यानी हाइपर टेक्स्ट मार्कअप लैंग्वेज।"},
    {"q_en": "Which tag creates the largest heading in HTML?", "q_hi": "HTML में सबसे बड़ा शीर्षक कौन-सा टैग बनाता है?",
     "options_en": ["<h6>", "<h1>", "<head>", "<heading>"], "options_hi": ["<h6>", "<h1>", "<head>", "<heading>"],
     "a": 1, "exp_en": "<h1> is the largest; <h6> is smallest.", "exp_hi": "<h1> सबसे बड़ा शीर्षक है।"},
    {"q_en": "CSS stands for?", "q_hi": "CSS का पूर्ण रूप क्या है?",
     "options_en": ["Cascading Style Sheets", "Computer Style Sheets", "Creative Style System", "Colorful Style Sheets"], "options_hi": ["कैस्केडिंग स्टाइल शीट्स", "कंप्यूटर स्टाइल शीट्स", "क्रिएटिव स्टाइल सिस्टम", "कलरफुल स्टाइल शीट्स"],
     "a": 0, "exp_en": "CSS = Cascading Style Sheets.", "exp_hi": "CSS यानी कैस्केडिंग स्टाइल शीट्स।"},
    {"q_en": "Which tag inserts an image in HTML?", "q_hi": "HTML में चित्र जोड़ने वाला टैग कौन-सा है?",
     "options_en": ["<img>", "<image>", "<pic>", "<src>"], "options_hi": ["<img>", "<image>", "<pic>", "<src>"],
     "a": 0, "exp_en": "<img src='...'> inserts an image.", "exp_hi": "<img> टैग से चित्र जोड़ा जाता है।"},
    {"q_en": "Which tag is used to create a hyperlink?", "q_hi": "हाइपरलिंक बनाने के लिए कौन-सा टैग प्रयोग होता है?",
     "options_en": ["<link>", "<a>", "<href>", "<url>"], "options_hi": ["<link>", "<a>", "<href>", "<url>"],
     "a": 1, "exp_en": "<a href='...'> creates hyperlinks.", "exp_hi": "<a> टैग से हाइपरलिंक बनता है।"},
    {"q_en": "Which CSS property changes text color?", "q_hi": "पाठ का रंग बदलने के लिए कौन-सी CSS प्रॉपर्टी है?",
     "options_en": ["font-color", "text-color", "color", "foreground"], "options_hi": ["font-color", "text-color", "color", "foreground"],
     "a": 2, "exp_en": "'color' sets text color in CSS.", "exp_hi": "CSS में 'color' से टेक्स्ट का रंग बदलता है।"},
    {"q_en": "Which HTML5 tag embeds a video?", "q_hi": "HTML5 में वीडियो जोड़ने वाला टैग कौन-सा है?",
     "options_en": ["<video>", "<media>", "<movie>", "<play>"], "options_hi": ["<video>", "<media>", "<movie>", "<play>"],
     "a": 0, "exp_en": "<video> is new in HTML5 for embedding videos.", "exp_hi": "HTML5 में <video> टैग से वीडियो जोड़ा जाता है।"},
    {"q_en": "Which attribute specifies alternate text for an image?", "q_hi": "चित्र के लिए वैकल्पिक पाठ कौन-सा एट्रिब्यूट बताता है?",
     "options_en": ["title", "alt", "src", "longdesc"], "options_hi": ["title", "alt", "src", "longdesc"],
     "a": 1, "exp_en": "'alt' provides alternate text for images.", "exp_hi": "'alt' चित्र के लिए वैकल्पिक पाठ देता है।"},
    {"q_en": "JavaScript is primarily used for?", "q_hi": "जावास्क्रिप्ट मुख्यतः किसके लिए प्रयोग होती है?",
     "options_en": ["Styling pages", "Structuring pages", "Client-side interactivity", "Database management"], "options_hi": ["पेज स्टाइलिंग", "पेज संरचना", "क्लाइंट-साइड इंटरएक्टिविटी", "डेटाबेस प्रबंधन"],
     "a": 2, "exp_en": "JavaScript adds interactivity on the client side.", "exp_hi": "जावास्क्रिप्ट क्लाइंट-साइड पर इंटरएक्टिविटी देती है।"},
    {"q_en": "Which tag creates an unordered list?", "q_hi": "बिना क्रम वाली सूची (unordered list) कौन-सा टैग बनाता है?",
     "options_en": ["<ol>", "<ul>", "<li>", "<list>"], "options_hi": ["<ol>", "<ul>", "<li>", "<list>"],
     "a": 1, "exp_en": "<ul> creates unordered (bulleted) list.", "exp_hi": "<ul> बिंदु वाली सूची बनाता है।"},
    {"q_en": "What symbol prefixes a class selector in CSS?", "q_hi": "CSS में क्लास सेलेक्टर का चिह्न क्या है?",
     "options_en": ["#", ".", "*", "@"], "options_hi": ["#", ".", "*", "@"],
     "a": 1, "exp_en": "Class selectors start with a dot (.).", "exp_hi": "क्लास सेलेक्टर बिंदु (.) से शुरू होता है।"},
    {"q_en": "What symbol prefixes an ID selector in CSS?", "q_hi": "CSS में ID सेलेक्टर का चिह्न क्या है?",
     "options_en": ["#", ".", "&", "$"], "options_hi": ["#", ".", "&", "$"],
     "a": 0, "exp_en": "ID selector uses '#'.", "exp_hi": "ID सेलेक्टर '#' से शुरू होता है।"},
    {"q_en": "Which HTML element defines the page title?", "q_hi": "पेज का शीर्षक कौन-सा टैग निर्धारित करता है?",
     "options_en": ["<meta>", "<head>", "<title>", "<h1>"], "options_hi": ["<meta>", "<head>", "<title>", "<h1>"],
     "a": 2, "exp_en": "<title> sets the browser tab / document title.", "exp_hi": "<title> ब्राउज़र टैब का शीर्षक बनाता है।"},
    {"q_en": "What does the <br> tag do?", "q_hi": "<br> टैग का कार्य क्या है?",
     "options_en": ["Bold text", "Line break", "Remove border", "Background"], "options_hi": ["बोल्ड टेक्स्ट", "पंक्ति तोड़ना", "बॉर्डर हटाना", "पृष्ठभूमि"],
     "a": 1, "exp_en": "<br> inserts a line break.", "exp_hi": "<br> पंक्ति तोड़ता है।"},
    {"q_en": "Which is the correct DOCTYPE for HTML5?", "q_hi": "HTML5 के लिए सही DOCTYPE कौन-सा है?",
     "options_en": ["<!DOCTYPE html5>", "<!DOCTYPE html>", "<DOCTYPE HTML>", "<!HTML5>"], "options_hi": ["<!DOCTYPE html5>", "<!DOCTYPE html>", "<DOCTYPE HTML>", "<!HTML5>"],
     "a": 1, "exp_en": "HTML5 uses simple '<!DOCTYPE html>'.", "exp_hi": "HTML5 में सरल '<!DOCTYPE html>' होता है।"},
    {"q_en": "Inline CSS is applied using which attribute?", "q_hi": "इनलाइन CSS किस एट्रिब्यूट से लगाई जाती है?",
     "options_en": ["class", "id", "style", "css"], "options_hi": ["class", "id", "style", "css"],
     "a": 2, "exp_en": "style attribute applies inline CSS.", "exp_hi": "style एट्रिब्यूट से इनलाइन CSS लगती है।"},
    {"q_en": "Which property sets background color?", "q_hi": "पृष्ठभूमि का रंग कौन-सी प्रॉपर्टी निर्धारित करती है?",
     "options_en": ["bgcolor", "background-color", "color-bg", "back-color"], "options_hi": ["bgcolor", "background-color", "color-bg", "back-color"],
     "a": 1, "exp_en": "'background-color' sets background.", "exp_hi": "'background-color' से पृष्ठभूमि रंग सेट होता है।"},
    {"q_en": "Which type attribute submits an HTML form?", "q_hi": "HTML फ़ॉर्म सबमिट करने वाला बटन type क्या होता है?",
     "options_en": ["send", "submit", "form-send", "post"], "options_hi": ["send", "submit", "form-send", "post"],
     "a": 1, "exp_en": "type=\"submit\" submits the form.", "exp_hi": "type=\"submit\" फ़ॉर्म सबमिट करता है।"},
    {"q_en": "Which tag defines a table row?", "q_hi": "तालिका की पंक्ति कौन-सा टैग बनाता है?",
     "options_en": ["<td>", "<tr>", "<th>", "<row>"], "options_hi": ["<td>", "<tr>", "<th>", "<row>"],
     "a": 1, "exp_en": "<tr> is table row; <td> is cell.", "exp_hi": "<tr> पंक्ति और <td> सेल बनाता है।"},
    {"q_en": "Which CSS property controls space inside the border?", "q_hi": "बॉर्डर के अंदर की जगह कौन-सी CSS प्रॉपर्टी नियंत्रित करती है?",
     "options_en": ["margin", "padding", "spacing", "border-space"], "options_hi": ["margin", "padding", "spacing", "border-space"],
     "a": 1, "exp_en": "Padding is inside the border; margin is outside.", "exp_hi": "पैडिंग बॉर्डर के अंदर की जगह है।"},
    {"q_en": "Which HTML5 semantic tag represents navigation?", "q_hi": "नेविगेशन के लिए HTML5 का सीमेंटिक टैग कौन-सा है?",
     "options_en": ["<nav>", "<div>", "<menu>", "<links>"], "options_hi": ["<nav>", "<div>", "<menu>", "<links>"],
     "a": 0, "exp_en": "<nav> is the semantic tag for navigation.", "exp_hi": "<nav> नेविगेशन के लिए है।"},
    {"q_en": "Which hex color code is red?", "q_hi": "लाल रंग का हेक्स कोड कौन-सा है?",
     "options_en": ["#00FF00", "#FF0000", "#0000FF", "#FFFF00"], "options_hi": ["#00FF00", "#FF0000", "#0000FF", "#FFFF00"],
     "a": 1, "exp_en": "#FF0000 is pure red.", "exp_hi": "#FF0000 शुद्ध लाल रंग है।"},
    {"q_en": "What does responsive design mean?", "q_hi": "रेस्पॉन्सिव डिज़ाइन का क्या अर्थ है?",
     "options_en": ["Fast loading", "Adapts to screen size", "Heavy graphics", "Good animations"], "options_hi": ["तेज़ लोडिंग", "स्क्रीन आकार के अनुसार बदलना", "भारी ग्राफ़िक्स", "अच्छे एनिमेशन"],
     "a": 1, "exp_en": "Responsive design adjusts to different screen sizes.", "exp_hi": "रेस्पॉन्सिव डिज़ाइन स्क्रीन आकार के अनुसार बदलता है।"},
    {"q_en": "What is the meta viewport tag used for?", "q_hi": "मेटा व्यूपोर्ट टैग किसलिए प्रयोग होता है?",
     "options_en": ["SEO", "Responsive scaling on mobile", "Security", "Styling"], "options_hi": ["SEO", "मोबाइल पर रेस्पॉन्सिव स्केलिंग", "सुरक्षा", "स्टाइलिंग"],
     "a": 1, "exp_en": "Viewport meta controls page scaling on mobile.", "exp_hi": "यह मोबाइल पर पेज का स्केल तय करता है।"},
    {"q_en": "Which tag represents a horizontal rule?", "q_hi": "क्षैतिज रेखा (horizontal rule) किस टैग से बनती है?",
     "options_en": ["<p>", "<br>", "<hr>", "<lb>"], "options_hi": ["<p>", "<br>", "<hr>", "<lb>"],
     "a": 2, "exp_en": "<hr> gives a horizontal rule.", "exp_hi": "<hr> क्षैतिज रेखा बनाता है।"},
    {"q_en": "Which CSS unit is relative to parent font size?", "q_hi": "कौन-सी CSS इकाई मूल फ़ॉन्ट आकार के सापेक्ष होती है?",
     "options_en": ["px", "em", "%", "cm"], "options_hi": ["px", "em", "%", "cm"],
     "a": 1, "exp_en": "'em' is relative to the parent element's font size.", "exp_hi": "'em' पैरेंट एलिमेंट के फ़ॉन्ट आकार के सापेक्ष होती है।"},
    {"q_en": "Which CSS property hides an element but keeps space?", "q_hi": "एलिमेंट को छुपाने पर भी जगह रखने वाली CSS प्रॉपर्टी कौन-सी है?",
     "options_en": ["display: none", "visibility: hidden", "opacity: 0 only", "hide: true"], "options_hi": ["display: none", "visibility: hidden", "केवल opacity: 0", "hide: true"],
     "a": 1, "exp_en": "visibility: hidden hides element but preserves its space.", "exp_hi": "visibility: hidden छुपाता है पर जगह रखता है।"},
    {"q_en": "What does HTML stand for in simple terms?", "q_hi": "सरल शब्दों में HTML क्या है?",
     "options_en": ["Styling language", "Markup language for web pages", "Programming language", "Database query"], "options_hi": ["स्टाइलिंग भाषा", "वेब पेज की मार्कअप भाषा", "प्रोग्रामिंग भाषा", "डेटाबेस क्वेरी"],
     "a": 1, "exp_en": "HTML is a markup language used to create web pages.", "exp_hi": "HTML वेब पेज बनाने की मार्कअप भाषा है।"},
    {"q_en": "Which CSS property makes text bold?", "q_hi": "पाठ को बोल्ड कौन-सी CSS प्रॉपर्टी करती है?",
     "options_en": ["font-weight", "text-style", "font-bold", "weight"], "options_hi": ["font-weight", "text-style", "font-bold", "weight"],
     "a": 0, "exp_en": "font-weight: bold makes text bold.", "exp_hi": "font-weight: bold से टेक्स्ट बोल्ड होता है।"},
    {"q_en": "Which selector selects all elements?", "q_hi": "सभी एलिमेंट्स को कौन-सा सेलेक्टर चुनता है?",
     "options_en": ["*", "all", ".all", "#all"], "options_hi": ["*", "all", ".all", "#all"],
     "a": 0, "exp_en": "'*' is the universal selector.", "exp_hi": "'*' यूनिवर्सल सेलेक्टर है।"},
    {"q_en": "What does the <head> tag contain?", "q_hi": "<head> टैग में क्या होता है?",
     "options_en": ["Visible page body", "Metadata like title, links", "Footer", "Only images"], "options_hi": ["दिखने वाला पेज बॉडी", "शीर्षक, लिंक जैसे मेटाडेटा", "पाद-टिप्पणी", "केवल चित्र"],
     "a": 1, "exp_en": "<head> holds metadata (title, links, meta tags).", "exp_hi": "<head> में पेज का मेटाडेटा होता है।"},
    {"q_en": "Which tag defines a paragraph?", "q_hi": "पैराग्राफ किस टैग से बनता है?",
     "options_en": ["<para>", "<p>", "<pg>", "<pr>"], "options_hi": ["<para>", "<p>", "<pg>", "<pr>"],
     "a": 1, "exp_en": "<p> defines a paragraph.", "exp_hi": "<p> पैराग्राफ बनाता है।"},
    {"q_en": "Which is the most common text format for web?", "q_hi": "वेब के लिए सबसे सामान्य पाठ प्रारूप कौन-सा है?",
     "options_en": ["UTF-8", "ASCII only", "Unicode-32", "Binary"], "options_hi": ["UTF-8", "केवल ASCII", "यूनिकोड-32", "बाइनरी"],
     "a": 0, "exp_en": "UTF-8 is the standard text encoding for the web.", "exp_hi": "वेब पर UTF-8 मानक पाठ एन्कोडिंग है।"},
    {"q_en": "Which element is used for the largest button-like label?", "q_hi": "बटन जैसे लेबल के लिए कौन-सा टैग है?",
     "options_en": ["<btn>", "<button>", "<click>", "<a>"], "options_hi": ["<btn>", "<button>", "<click>", "<a>"],
     "a": 1, "exp_en": "<button> creates a clickable button.", "exp_hi": "<button> क्लिक करने योग्य बटन बनाता है।"},
    {"q_en": "Which HTML tag is used for bold text (semantic importance)?", "q_hi": "अर्थपूर्ण बोल्ड पाठ के लिए कौन-सा टैग है?",
     "options_en": ["<bold>", "<strong>", "<b-text>", "<imp>"], "options_hi": ["<bold>", "<strong>", "<b-text>", "<imp>"],
     "a": 1, "exp_en": "<strong> conveys semantic emphasis (and renders bold).", "exp_hi": "<strong> अर्थपूर्ण ज़ोर देता है और बोल्ड दिखता है।"},
    {"q_en": "What is SEO?", "q_hi": "SEO क्या है?",
     "options_en": ["Search Engine Optimization", "Secure Email Operation", "Site Editing Online", "Server Engine Option"], "options_hi": ["सर्च इंजन ऑप्टिमाइज़ेशन", "सुरक्षित ईमेल संचालन", "साइट संपादन ऑनलाइन", "सर्वर इंजन विकल्प"],
     "a": 0, "exp_en": "SEO = Search Engine Optimization.", "exp_hi": "SEO यानी सर्च इंजन ऑप्टिमाइज़ेशन।"},
    {"q_en": "Which tag is used for italic text (semantic)?", "q_hi": "अर्थपूर्ण इटैलिक टेक्स्ट के लिए कौन-सा टैग है?",
     "options_en": ["<italic>", "<i>", "<em>", "<it>"], "options_hi": ["<italic>", "<i>", "<em>", "<it>"],
     "a": 2, "exp_en": "<em> adds semantic emphasis and renders italic.", "exp_hi": "<em> अर्थपूर्ण ज़ोर देता है और इटैलिक दिखता है।"},
    {"q_en": "Which CSS property sets the size of text?", "q_hi": "पाठ का आकार कौन-सी CSS प्रॉपर्टी निर्धारित करती है?",
     "options_en": ["font-size", "text-size", "size", "font"], "options_hi": ["font-size", "text-size", "size", "font"],
     "a": 0, "exp_en": "font-size sets the text size.", "exp_hi": "font-size से पाठ का आकार तय होता है।"},
    {"q_en": "Which HTML attribute specifies the target window of a link?", "q_hi": "लिंक की लक्ष्य विंडो कौन-सा एट्रिब्यूट बताता है?",
     "options_en": ["href", "target", "rel", "link"], "options_hi": ["href", "target", "rel", "link"],
     "a": 1, "exp_en": "target='_blank' opens link in a new tab.", "exp_hi": "target='_blank' लिंक को नए टैब में खोलता है।"},
    {"q_en": "Which tag is used for the footer section?", "q_hi": "पाद-खंड (footer) के लिए कौन-सा टैग है?",
     "options_en": ["<foot>", "<footer>", "<bottom>", "<end>"], "options_hi": ["<foot>", "<footer>", "<bottom>", "<end>"],
     "a": 1, "exp_en": "<footer> is the semantic footer tag in HTML5.", "exp_hi": "<footer> HTML5 का सीमेंटिक पाद टैग है।"},
    {"q_en": "CSS stands for style sheets that are?", "q_hi": "CSS का कार्य शैली का प्रकार है?",
     "options_en": ["Client-side programming", "Presentation/styling", "Server scripting", "Data format"], "options_hi": ["क्लाइंट-साइड प्रोग्रामिंग", "प्रस्तुति/स्टाइलिंग", "सर्वर स्क्रिप्टिंग", "डेटा प्रारूप"],
     "a": 1, "exp_en": "CSS handles presentation (styling).", "exp_hi": "CSS पेज की प्रस्तुति को नियंत्रित करता है।"},
    {"q_en": "Which CSS display value makes an element invisible and takes no space?", "q_hi": "एलिमेंट अदृश्य और जगह न ले, इसके लिए display मान कौन-सा है?",
     "options_en": ["none", "hidden", "invisible", "gone"], "options_hi": ["none", "hidden", "invisible", "gone"],
     "a": 0, "exp_en": "display: none removes element from layout.", "exp_hi": "display: none एलिमेंट को लेआउट से हटा देता है।"},
    {"q_en": "Which method posts form data to server?", "q_hi": "फ़ॉर्म डेटा सर्वर पर भेजने की विधि कौन-सी है?",
     "options_en": ["GET", "POST", "PUSH", "SEND"], "options_hi": ["GET", "POST", "PUSH", "SEND"],
     "a": 1, "exp_en": "POST sends form data in the body of the request.", "exp_hi": "POST रिक्वेस्ट के बॉडी में डेटा भेजता है।"},
    {"q_en": "Which tag embeds audio in HTML5?", "q_hi": "HTML5 में ऑडियो जोड़ने वाला टैग कौन-सा है?",
     "options_en": ["<audio>", "<sound>", "<music>", "<media>"], "options_hi": ["<audio>", "<sound>", "<music>", "<media>"],
     "a": 0, "exp_en": "<audio> embeds sound content.", "exp_hi": "<audio> ध्वनि जोड़ता है।"},
    {"q_en": "What does CSS 'margin: auto' commonly do for a block element?", "q_hi": "ब्लॉक एलिमेंट पर 'margin: auto' आमतौर पर क्या करता है?",
     "options_en": ["Removes margin", "Centers horizontally", "Aligns right", "Does nothing"], "options_hi": ["मार्जिन हटाता है", "क्षैतिज रूप से केंद्रित करता है", "दाएँ संरेखित करता है", "कुछ नहीं"],
     "a": 1, "exp_en": "On a block with a set width, margin auto centers it horizontally.", "exp_hi": "चौड़ाई वाले ब्लॉक को margin auto क्षैतिज मध्य में लाता है।"},
    {"q_en": "Which of the following is a JavaScript framework/library?", "q_hi": "इनमें से कौन-सा जावास्क्रिप्ट फ्रेमवर्क/लाइब्रेरी है?",
     "options_en": ["Laravel", "React", "Django", "Flask"], "options_hi": ["लारावेल", "रीएक्ट", "जैंगो", "फ्लास्क"],
     "a": 1, "exp_en": "React is a JavaScript library for building UIs.", "exp_hi": "React एक जावास्क्रिप्ट लाइब्रेरी है।"},
    {"q_en": "What does a WYSIWYG editor show?", "q_hi": "WYSIWYG संपादक क्या दिखाता है?",
     "options_en": ["Raw code only", "What You See Is What You Get (visual result)", "Only wireframes", "Only console"], "options_hi": ["केवल कच्चा कोड", "जो दिखे वही मिलेगा (दृश्य परिणाम)", "केवल वायरफ्रेम", "केवल कंसोल"],
     "a": 1, "exp_en": "WYSIWYG means you see the final output while editing.", "exp_hi": "WYSIWYG में संपादन के दौरान अंतिम परिणाम दिखता है।"},
    {"q_en": "Which of these is NOT a CSS framework?", "q_hi": "इनमें से कौन-सा CSS फ्रेमवर्क नहीं है?",
     "options_en": ["Tailwind CSS", "Bootstrap", "Bulma", "Express"], "options_hi": ["टेलविंड CSS", "बूटस्ट्रैप", "बुल्मा", "एक्सप्रेस"],
     "a": 3, "exp_en": "Express is a Node.js backend framework, not CSS.", "exp_hi": "Express Node.js का बैकएंड फ्रेमवर्क है।"},
]

M3 = [
    {"q_en": "Who created Python?", "q_hi": "पायथन के निर्माता कौन हैं?",
     "options_en": ["James Gosling", "Guido van Rossum", "Dennis Ritchie", "Bjarne Stroustrup"], "options_hi": ["जेम्स गॉसलिंग", "गिडो वैन रॉसम", "डेनिस रिची", "ब्यार्ने स्ट्रॉस्ट्रप"],
     "a": 1, "exp_en": "Guido van Rossum created Python in 1991.", "exp_hi": "गिडो वैन रॉसम ने 1991 में पायथन बनाया।"},
    {"q_en": "Which symbol starts a single-line comment in Python?", "q_hi": "पायथन में एकल पंक्ति टिप्पणी का चिह्न कौन-सा है?",
     "options_en": ["//", "#", "/* */", "--"], "options_hi": ["//", "#", "/* */", "--"],
     "a": 1, "exp_en": "Python uses '#' for single-line comments.", "exp_hi": "पायथन में '#' टिप्पणी के लिए प्रयोग होता है।"},
    {"q_en": "Which of these is a mutable data type?", "q_hi": "इनमें से कौन-सा परिवर्तनीय (mutable) डेटा प्रकार है?",
     "options_en": ["tuple", "string", "list", "int"], "options_hi": ["ट्यूपल", "स्ट्रिंग", "लिस्ट", "इंट"],
     "a": 2, "exp_en": "List is mutable; others are immutable.", "exp_hi": "लिस्ट परिवर्तनीय है, बाकी नहीं।"},
    {"q_en": "What is the output of print(2 ** 3)?", "q_hi": "print(2 ** 3) का आउटपुट क्या है?",
     "options_en": ["6", "8", "9", "5"], "options_hi": ["6", "8", "9", "5"],
     "a": 1, "exp_en": "** is the exponent operator; 2³ = 8.", "exp_hi": "** घातांक संकारक है; 2³ = 8।"},
    {"q_en": "Which keyword defines a function in Python?", "q_hi": "पायथन में फंक्शन कौन-से कीवर्ड से परिभाषित होता है?",
     "options_en": ["function", "def", "fun", "define"], "options_hi": ["function", "def", "fun", "define"],
     "a": 1, "exp_en": "'def' defines a function.", "exp_hi": "'def' कीवर्ड से फंक्शन बनता है।"},
    {"q_en": "Where does indexing start in a Python list?", "q_hi": "पायथन लिस्ट में इंडेक्सिंग कहाँ से शुरू होती है?",
     "options_en": ["0", "1", "-1", "Depends"], "options_hi": ["0", "1", "-1", "निर्भर करता है"],
     "a": 0, "exp_en": "Python list indices start from 0.", "exp_hi": "पायथन लिस्ट इंडेक्स 0 से शुरू होता है।"},
    {"q_en": "Which operator performs integer (floor) division?", "q_hi": "पूर्णांक (फ्लोर) विभाजन कौन-सा ऑपरेटर करता है?",
     "options_en": ["/", "//", "%", "**"], "options_hi": ["/", "//", "%", "**"],
     "a": 1, "exp_en": "// is floor division in Python.", "exp_hi": "// पायथन में फ्लोर विभाजन है।"},
    {"q_en": "Output of len('Python')?", "q_hi": "len('Python') का आउटपुट क्या है?",
     "options_en": ["5", "6", "7", "Error"], "options_hi": ["5", "6", "7", "त्रुटि"],
     "a": 1, "exp_en": "'Python' has 6 characters.", "exp_hi": "'Python' में 6 अक्षर हैं।"},
    {"q_en": "Which function takes user input?", "q_hi": "उपयोगकर्ता से इनपुट लेने वाला फंक्शन कौन-सा है?",
     "options_en": ["scan()", "read()", "input()", "get()"], "options_hi": ["scan()", "read()", "input()", "get()"],
     "a": 2, "exp_en": "input() reads string from the user.", "exp_hi": "input() उपयोगकर्ता से स्ट्रिंग लेता है।"},
    {"q_en": "What is the Python file extension?", "q_hi": "पायथन फ़ाइल का एक्सटेंशन क्या है?",
     "options_en": [".pyt", ".py", ".python", ".p"], "options_hi": [".pyt", ".py", ".python", ".p"],
     "a": 1, "exp_en": "Python files use .py.", "exp_hi": "पायथन फ़ाइलें .py होती हैं।"},
    {"q_en": "How do you create a tuple?", "q_hi": "ट्यूपल कैसे बनाते हैं?",
     "options_en": ["[1,2,3]", "(1,2,3)", "{1,2,3}", "<1,2,3>"], "options_hi": ["[1,2,3]", "(1,2,3)", "{1,2,3}", "<1,2,3>"],
     "a": 1, "exp_en": "Tuples use parentheses ().", "exp_hi": "ट्यूपल को कोष्ठक () से बनाते हैं।"},
    {"q_en": "Dictionary syntax in Python?", "q_hi": "पायथन में डिक्शनरी का वाक्य-विन्यास कौन-सा है?",
     "options_en": ["{key: value}", "[key: value]", "(key: value)", "<key=value>"], "options_hi": ["{key: value}", "[key: value]", "(key: value)", "<key=value>"],
     "a": 0, "exp_en": "Dictionaries use curly braces with key:value pairs.", "exp_hi": "डिक्शनरी {key: value} रूप में बनती है।"},
    {"q_en": "Which construct handles exceptions?", "q_hi": "अपवाद प्रबंधन किसके द्वारा होता है?",
     "options_en": ["try-except", "if-else", "do-while", "catch-throw"], "options_hi": ["try-except", "if-else", "do-while", "catch-throw"],
     "a": 0, "exp_en": "try-except handles exceptions in Python.", "exp_hi": "पायथन में try-except अपवाद संभालता है।"},
    {"q_en": "Boolean values in Python are?", "q_hi": "पायथन में बूलियन मान क्या होते हैं?",
     "options_en": ["true/false", "True/False", "TRUE/FALSE", "1/0 only"], "options_hi": ["true/false", "True/False", "TRUE/FALSE", "केवल 1/0"],
     "a": 1, "exp_en": "Python uses True and False (capitalized).", "exp_hi": "पायथन में True और False होते हैं।"},
    {"q_en": "range(5) generates which numbers?", "q_hi": "range(5) कौन-सी संख्याएँ उत्पन्न करता है?",
     "options_en": ["1 to 5", "0 to 5", "0 to 4", "1 to 4"], "options_hi": ["1 से 5", "0 से 5", "0 से 4", "1 से 4"],
     "a": 2, "exp_en": "range(5) yields 0,1,2,3,4.", "exp_hi": "range(5) से 0,1,2,3,4 मिलते हैं।"},
    {"q_en": "Which of these is NOT a Python keyword?", "q_hi": "इनमें से कौन पायथन कीवर्ड नहीं है?",
     "options_en": ["class", "object", "def", "return"], "options_hi": ["class", "object", "def", "return"],
     "a": 1, "exp_en": "'object' is a built-in class, not a keyword.", "exp_hi": "'object' कीवर्ड नहीं, एक बिल्ट-इन क्लास है।"},
    {"q_en": "How do you create a multi-line string?", "q_hi": "बहु-पंक्ति स्ट्रिंग कैसे बनाते हैं?",
     "options_en": ["'text'", "\"text\"", "\"\"\"text\"\"\"", "<<text>>"], "options_hi": ["'text'", "\"text\"", "\"\"\"text\"\"\"", "<<text>>"],
     "a": 2, "exp_en": "Triple quotes create multi-line strings.", "exp_hi": "ट्रिपल कोट से बहु-पंक्ति स्ट्रिंग बनती है।"},
    {"q_en": "Output of print(10 % 3)?", "q_hi": "print(10 % 3) का आउटपुट क्या है?",
     "options_en": ["1", "3", "0", "3.33"], "options_hi": ["1", "3", "0", "3.33"],
     "a": 0, "exp_en": "% gives modulo; 10 mod 3 = 1.", "exp_hi": "% मॉड्यूलो; 10 mod 3 = 1।"},
    {"q_en": "Which module offers mathematical functions?", "q_hi": "गणितीय फंक्शन कौन-सा मॉड्यूल देता है?",
     "options_en": ["math", "maths", "numeric", "calc"], "options_hi": ["math", "maths", "numeric", "calc"],
     "a": 0, "exp_en": "import math gives math functions.", "exp_hi": "import math से गणितीय फंक्शन मिलते हैं।"},
    {"q_en": "What kind of language is Python?", "q_hi": "पायथन किस प्रकार की भाषा है?",
     "options_en": ["Compiled", "Interpreted", "Assembly", "Machine code"], "options_hi": ["कम्पाइल्ड", "इंटरप्रीटेड", "असेंबली", "मशीन कोड"],
     "a": 1, "exp_en": "Python is interpreted and dynamically typed.", "exp_hi": "पायथन इंटरप्रीटेड और डायनेमिकली टाइप्ड है।"},
    {"q_en": "What does list.append(x) do?", "q_hi": "list.append(x) का कार्य क्या है?",
     "options_en": ["Adds x at start", "Adds x at end", "Removes x", "Sorts list"], "options_hi": ["x को शुरू में जोड़ता है", "x को अंत में जोड़ता है", "x हटाता है", "सूची छाँटता है"],
     "a": 1, "exp_en": "append adds an element at the end.", "exp_hi": "append सूची के अंत में जोड़ता है।"},
    {"q_en": "Which method removes the last element of a list?", "q_hi": "सूची का अंतिम तत्व कौन-सी विधि हटाती है?",
     "options_en": ["remove()", "pop()", "delete()", "clear()"], "options_hi": ["remove()", "pop()", "delete()", "clear()"],
     "a": 1, "exp_en": "pop() removes and returns the last element by default.", "exp_hi": "pop() अंतिम तत्व हटाकर लौटाता है।"},
    {"q_en": "Which operator concatenates strings?", "q_hi": "स्ट्रिंग जोड़ने वाला ऑपरेटर कौन-सा है?",
     "options_en": ["+", "&", ".", ","], "options_hi": ["+", "&", ".", ","],
     "a": 0, "exp_en": "+ concatenates strings.", "exp_hi": "+ से स्ट्रिंग जुड़ती है।"},
    {"q_en": "Which function returns the type of a variable?", "q_hi": "चर का प्रकार कौन-सा फंक्शन लौटाता है?",
     "options_en": ["typeof()", "type()", "datatype()", "class()"], "options_hi": ["typeof()", "type()", "datatype()", "class()"],
     "a": 1, "exp_en": "type() returns the data type.", "exp_hi": "type() डेटा प्रकार लौटाता है।"},
    {"q_en": "Which data structure stores unique items only?", "q_hi": "कौन-सी डेटा संरचना केवल अद्वितीय आइटम रखती है?",
     "options_en": ["list", "tuple", "set", "dict"], "options_hi": ["लिस्ट", "ट्यूपल", "सेट", "डिक्ट"],
     "a": 2, "exp_en": "A set stores unique elements.", "exp_hi": "सेट में केवल अद्वितीय तत्व रहते हैं।"},
    {"q_en": "What is the output of 'Hi'*3?", "q_hi": "'Hi'*3 का आउटपुट क्या है?",
     "options_en": ["Hi3", "HiHiHi", "Error", "Hi Hi Hi"], "options_hi": ["Hi3", "HiHiHi", "त्रुटि", "Hi Hi Hi"],
     "a": 1, "exp_en": "Multiplying a string repeats it.", "exp_hi": "स्ट्रिंग को संख्या से गुणा करने पर वह दोहराई जाती है।"},
    {"q_en": "Which keyword exits a loop?", "q_hi": "लूप से बाहर निकलने का कीवर्ड कौन-सा है?",
     "options_en": ["exit", "break", "stop", "end"], "options_hi": ["exit", "break", "stop", "end"],
     "a": 1, "exp_en": "'break' exits the current loop.", "exp_hi": "'break' मौजूदा लूप समाप्त करता है।"},
    {"q_en": "Which keyword skips current iteration of a loop?", "q_hi": "लूप की मौजूदा पुनरावृत्ति छोड़ने वाला कीवर्ड कौन-सा है?",
     "options_en": ["skip", "continue", "pass", "next"], "options_hi": ["skip", "continue", "pass", "next"],
     "a": 1, "exp_en": "'continue' skips to the next iteration.", "exp_hi": "'continue' अगली पुनरावृत्ति पर जाता है।"},
    {"q_en": "Which statement is used to import a module?", "q_hi": "मॉड्यूल आयात करने का कथन कौन-सा है?",
     "options_en": ["include", "import", "using", "require"], "options_hi": ["include", "import", "using", "require"],
     "a": 1, "exp_en": "'import' brings in a module.", "exp_hi": "'import' से मॉड्यूल आयात होता है।"},
    {"q_en": "What is the result of bool('')?", "q_hi": "bool('') का परिणाम क्या है?",
     "options_en": ["True", "False", "Error", "None"], "options_hi": ["True", "False", "त्रुटि", "None"],
     "a": 1, "exp_en": "Empty string is falsy.", "exp_hi": "खाली स्ट्रिंग false मानी जाती है।"},
    {"q_en": "Which function converts string to integer?", "q_hi": "स्ट्रिंग को पूर्णांक में कौन-सा फंक्शन बदलता है?",
     "options_en": ["int()", "str()", "float()", "num()"], "options_hi": ["int()", "str()", "float()", "num()"],
     "a": 0, "exp_en": "int() converts to integer.", "exp_hi": "int() पूर्णांक में बदलता है।"},
    {"q_en": "What does 'pass' do?", "q_hi": "'pass' का कार्य क्या है?",
     "options_en": ["Stops program", "Does nothing (placeholder)", "Skips iteration", "Raises error"], "options_hi": ["प्रोग्राम रोकता है", "कुछ नहीं करता (प्लेसहोल्डर)", "पुनरावृत्ति छोड़ता है", "त्रुटि देता है"],
     "a": 1, "exp_en": "'pass' is a null statement acting as placeholder.", "exp_hi": "'pass' प्लेसहोल्डर है।"},
    {"q_en": "How do you check equality?", "q_hi": "समता (equality) कैसे जाँचते हैं?",
     "options_en": ["=", "==", "===", "equals"], "options_hi": ["=", "==", "===", "equals"],
     "a": 1, "exp_en": "== checks value equality.", "exp_hi": "== दो मानों की समता जाँचता है।"},
    {"q_en": "Which is the logical AND operator in Python?", "q_hi": "पायथन में लॉजिकल AND ऑपरेटर कौन-सा है?",
     "options_en": ["&&", "AND", "and", "&"], "options_hi": ["&&", "AND", "and", "&"],
     "a": 2, "exp_en": "Python uses 'and' (lowercase).", "exp_hi": "पायथन में 'and' (छोटे अक्षर) है।"},
    {"q_en": "What does print(type(3.14)) output?", "q_hi": "print(type(3.14)) क्या आउटपुट देगा?",
     "options_en": ["<class 'int'>", "<class 'float'>", "<class 'double'>", "<class 'number'>"], "options_hi": ["<class 'int'>", "<class 'float'>", "<class 'double'>", "<class 'number'>"],
     "a": 1, "exp_en": "3.14 is a float.", "exp_hi": "3.14 float है।"},
    {"q_en": "What is slicing?", "q_hi": "स्लाइसिंग क्या है?",
     "options_en": ["Cutting physical objects", "Extracting part of a sequence", "Dividing numbers", "Stopping loop"], "options_hi": ["भौतिक वस्तुएँ काटना", "अनुक्रम का भाग निकालना", "संख्याएँ विभाजित करना", "लूप रोकना"],
     "a": 1, "exp_en": "Slicing extracts a sub-part of a sequence (e.g. s[1:4]).", "exp_hi": "स्लाइसिंग अनुक्रम से भाग निकालती है (जैसे s[1:4])।"},
    {"q_en": "Which method converts all characters to uppercase?", "q_hi": "सभी अक्षर बड़े करने वाली विधि कौन-सी है?",
     "options_en": ["upper()", "toUpper()", "uppercase()", "caps()"], "options_hi": ["upper()", "toUpper()", "uppercase()", "caps()"],
     "a": 0, "exp_en": "str.upper() returns uppercase.", "exp_hi": "str.upper() बड़े अक्षरों में बदलता है।"},
    {"q_en": "Which is a floating-point literal?", "q_hi": "इनमें से कौन एक फ्लोट लिटरल है?",
     "options_en": ["10", "'10'", "10.0", "ten"], "options_hi": ["10", "'10'", "10.0", "ten"],
     "a": 2, "exp_en": "10.0 is a float literal.", "exp_hi": "10.0 फ्लोट लिटरल है।"},
    {"q_en": "Which built-in function gives number of items?", "q_hi": "वस्तुओं की संख्या कौन-सा बिल्ट-इन फंक्शन देता है?",
     "options_en": ["size()", "length()", "len()", "count()"], "options_hi": ["size()", "length()", "len()", "count()"],
     "a": 2, "exp_en": "len() returns length.", "exp_hi": "len() लम्बाई लौटाता है।"},
    {"q_en": "In Python, lists are defined with which brackets?", "q_hi": "पायथन में लिस्ट किस कोष्ठक से बनती है?",
     "options_en": ["()", "[]", "{}", "<>"], "options_hi": ["()", "[]", "{}", "<>"],
     "a": 1, "exp_en": "Lists use square brackets [].", "exp_hi": "लिस्ट चौकोर कोष्ठक [] से बनती है।"},
    {"q_en": "What does print(10 / 4) output?", "q_hi": "print(10 / 4) का आउटपुट क्या है?",
     "options_en": ["2", "2.5", "2.0", "3"], "options_hi": ["2", "2.5", "2.0", "3"],
     "a": 1, "exp_en": "/ returns float division: 10/4 = 2.5.", "exp_hi": "/ फ्लोट विभाजन: 10/4 = 2.5।"},
    {"q_en": "Which keyword creates a class?", "q_hi": "क्लास बनाने का कीवर्ड कौन-सा है?",
     "options_en": ["class", "def", "create", "object"], "options_hi": ["class", "def", "create", "object"],
     "a": 0, "exp_en": "'class' defines a class.", "exp_hi": "'class' कीवर्ड से क्लास बनती है।"},
    {"q_en": "Which method reads a line from the user as string?", "q_hi": "उपयोगकर्ता से पंक्ति स्ट्रिंग के रूप में कौन पढ़ता है?",
     "options_en": ["readline", "input", "scan", "gets"], "options_hi": ["readline", "input", "scan", "gets"],
     "a": 1, "exp_en": "input() returns a string.", "exp_hi": "input() स्ट्रिंग लौटाता है।"},
    {"q_en": "What does 'None' represent?", "q_hi": "'None' किसका प्रतिनिधित्व करता है?",
     "options_en": ["Zero", "Empty string", "Absence of value", "False only"], "options_hi": ["शून्य", "खाली स्ट्रिंग", "मान की अनुपस्थिति", "केवल False"],
     "a": 2, "exp_en": "None represents the absence of a value.", "exp_hi": "None मान की अनुपस्थिति दर्शाता है।"},
    {"q_en": "Which operator is used for exponentiation?", "q_hi": "घातांक के लिए कौन-सा ऑपरेटर है?",
     "options_en": ["^", "**", "exp", "//"], "options_hi": ["^", "**", "exp", "//"],
     "a": 1, "exp_en": "** is the exponent operator in Python.", "exp_hi": "पायथन में ** घातांक ऑपरेटर है।"},
    {"q_en": "What is a function in Python?", "q_hi": "पायथन में फंक्शन क्या है?",
     "options_en": ["A variable", "A reusable block of code", "A data type", "A library"], "options_hi": ["एक चर", "पुनः प्रयोग योग्य कोड ब्लॉक", "एक डेटा प्रकार", "एक लाइब्रेरी"],
     "a": 1, "exp_en": "A function is a reusable block of code.", "exp_hi": "फंक्शन पुनः प्रयोग योग्य कोड ब्लॉक है।"},
    {"q_en": "Which loop iterates over a sequence?", "q_hi": "अनुक्रम पर बारी-बारी चलने वाला लूप कौन-सा है?",
     "options_en": ["while", "for", "do", "foreach"], "options_hi": ["while", "for", "do", "foreach"],
     "a": 1, "exp_en": "'for' iterates over sequences.", "exp_hi": "'for' अनुक्रम पर चलता है।"},
    {"q_en": "How do you open a file in Python?", "q_hi": "पायथन में फ़ाइल कैसे खोलते हैं?",
     "options_en": ["file.open()", "open(filename)", "new File()", "File(filename)"], "options_hi": ["file.open()", "open(filename)", "new File()", "File(filename)"],
     "a": 1, "exp_en": "open(filename, mode) is the builtin.", "exp_hi": "open(filename, mode) से फ़ाइल खुलती है।"},
    {"q_en": "Which package manager installs Python libraries?", "q_hi": "पायथन लाइब्रेरियाँ स्थापित करने वाला पैकेज मैनेजर कौन-सा है?",
     "options_en": ["npm", "pip", "gem", "apt"], "options_hi": ["npm", "pip", "gem", "apt"],
     "a": 1, "exp_en": "pip installs Python packages.", "exp_hi": "pip पायथन पैकेज स्थापित करता है।"},
]

M4 = [
    {"q_en": "What is the full form of IoT?", "q_hi": "IoT का पूर्ण रूप क्या है?",
     "options_en": ["Internet of Things", "Internet of Technology", "Intranet of Things", "Interface of Things"], "options_hi": ["इंटरनेट ऑफ थिंग्स", "इंटरनेट ऑफ टेक्नोलॉजी", "इंट्रानेट ऑफ थिंग्स", "इंटरफ़ेस ऑफ थिंग्स"],
     "a": 0, "exp_en": "IoT = Internet of Things.", "exp_hi": "IoT यानी इंटरनेट ऑफ थिंग्स।"},
    {"q_en": "What is the main role of sensors in IoT?", "q_hi": "IoT में सेंसर का मुख्य कार्य क्या है?",
     "options_en": ["Display data", "Collect environmental data", "Store data", "Print data"], "options_hi": ["डेटा दिखाना", "वातावरण से डेटा एकत्र करना", "डेटा संग्रह करना", "डेटा मुद्रित करना"],
     "a": 1, "exp_en": "Sensors capture data from the environment.", "exp_hi": "सेंसर वातावरण से डेटा इकट्ठा करते हैं।"},
    {"q_en": "Which protocol is popular in IoT?", "q_hi": "IoT में कौन-सा प्रोटोकॉल प्रचलित है?",
     "options_en": ["MQTT", "FTP", "SMTP", "POP3"], "options_hi": ["MQTT", "FTP", "SMTP", "POP3"],
     "a": 0, "exp_en": "MQTT is a lightweight IoT messaging protocol.", "exp_hi": "MQTT हल्का IoT मैसेजिंग प्रोटोकॉल है।"},
    {"q_en": "Arduino is a?", "q_hi": "Arduino क्या है?",
     "options_en": ["Operating System", "Microcontroller board", "Database", "Cloud service"], "options_hi": ["ऑपरेटिंग सिस्टम", "माइक्रोकंट्रोलर बोर्ड", "डेटाबेस", "क्लाउड सेवा"],
     "a": 1, "exp_en": "Arduino is an open-source microcontroller board.", "exp_hi": "Arduino एक ओपन-सोर्स माइक्रोकंट्रोलर बोर्ड है।"},
    {"q_en": "Which is an example of a smart home device?", "q_hi": "स्मार्ट होम उपकरण का उदाहरण कौन-सा है?",
     "options_en": ["Alexa", "Microwave", "Non-smart fridge", "Ceiling fan"], "options_hi": ["एलेक्सा", "माइक्रोवेव", "साधारण फ्रिज", "पंखा"],
     "a": 0, "exp_en": "Alexa is a smart voice assistant used in smart homes.", "exp_hi": "एलेक्सा स्मार्ट वॉइस असिस्टेंट है।"},
    {"q_en": "Which wireless tech is low-power and short-range, ideal for IoT?", "q_hi": "कौन-सी वायरलेस तकनीक कम बिजली, कम दूरी वाली IoT-अनुकूल है?",
     "options_en": ["Wi-Fi", "Bluetooth / Zigbee", "4G", "Fiber"], "options_hi": ["वाई-फाई", "ब्लूटूथ / ज़िगबी", "4G", "फाइबर"],
     "a": 1, "exp_en": "Bluetooth/Zigbee are low-power short-range.", "exp_hi": "ब्लूटूथ/ज़िगबी कम बिजली व कम दूरी की तकनीक हैं।"},
    {"q_en": "What is a Raspberry Pi?", "q_hi": "रास्पबेरी पाई क्या है?",
     "options_en": ["A fruit", "Single-board computer", "A sensor", "A router"], "options_hi": ["एक फल", "सिंगल-बोर्ड कंप्यूटर", "एक सेंसर", "एक राउटर"],
     "a": 1, "exp_en": "Raspberry Pi is a low-cost single-board computer.", "exp_hi": "रास्पबेरी पाई सस्ता सिंगल-बोर्ड कंप्यूटर है।"},
    {"q_en": "What does an actuator do?", "q_hi": "एक्चुएटर का कार्य क्या है?",
     "options_en": ["Sense environment", "Perform physical action", "Send email", "Store data"], "options_hi": ["वातावरण संवेदित करता है", "भौतिक क्रिया करता है", "ईमेल भेजता है", "डेटा संग्रह करता है"],
     "a": 1, "exp_en": "Actuators perform actions (motors, valves, switches).", "exp_hi": "एक्चुएटर भौतिक क्रिया करते हैं।"},
    {"q_en": "Which of the following is NOT an IoT layer?", "q_hi": "इनमें से कौन IoT की परत नहीं है?",
     "options_en": ["Perception", "Network", "Application", "Compilation"], "options_hi": ["परसेप्शन", "नेटवर्क", "एप्लिकेशन", "कम्पाइलेशन"],
     "a": 3, "exp_en": "IoT has perception, network and application layers.", "exp_hi": "IoT में परसेप्शन, नेटवर्क और एप्लिकेशन परतें होती हैं।"},
    {"q_en": "What role does cloud computing play in IoT?", "q_hi": "IoT में क्लाउड कंप्यूटिंग की भूमिका क्या है?",
     "options_en": ["None", "Data storage and processing", "Power supply", "Cooling"], "options_hi": ["कोई नहीं", "डेटा संग्रह और प्रसंस्करण", "बिजली आपूर्ति", "ठंडक"],
     "a": 1, "exp_en": "Cloud stores and processes large IoT data.", "exp_hi": "क्लाउड बड़े IoT डेटा को रखता और प्रोसेस करता है।"},
    {"q_en": "What does RFID stand for?", "q_hi": "RFID का पूर्ण रूप क्या है?",
     "options_en": ["Radio Frequency Identification", "Random Frequency Interface Device", "Remote Frequency Input Device", "None"], "options_hi": ["रेडियो फ्रीक्वेंसी आइडेंटिफ़िकेशन", "रैंडम फ्रीक्वेंसी इंटरफेस डिवाइस", "रिमोट फ्रीक्वेंसी इनपुट डिवाइस", "कोई नहीं"],
     "a": 0, "exp_en": "RFID = Radio Frequency Identification.", "exp_hi": "RFID यानी रेडियो फ्रीक्वेंसी आइडेंटिफ़िकेशन।"},
    {"q_en": "Who develops Arduino hardware/software?", "q_hi": "Arduino हार्डवेयर/सॉफ्टवेयर किसने बनाया?",
     "options_en": ["Google", "Microsoft", "Arduino LLC", "Intel"], "options_hi": ["गूगल", "माइक्रोसॉफ्ट", "Arduino LLC", "इंटेल"],
     "a": 2, "exp_en": "Arduino LLC develops the Arduino platform.", "exp_hi": "Arduino प्लेटफ़ॉर्म Arduino LLC बनाता है।"},
    {"q_en": "Sensor output can be?", "q_hi": "सेंसर का आउटपुट क्या हो सकता है?",
     "options_en": ["Digital only", "Analog only", "Both analog and digital", "Neither"], "options_hi": ["केवल डिजिटल", "केवल एनालॉग", "एनालॉग और डिजिटल दोनों", "कोई नहीं"],
     "a": 2, "exp_en": "Sensors can output analog or digital signals.", "exp_hi": "सेंसर एनालॉग या डिजिटल दोनों संकेत दे सकते हैं।"},
    {"q_en": "A smart watch is an example of which IoT category?", "q_hi": "स्मार्ट वॉच किस IoT श्रेणी का उदाहरण है?",
     "options_en": ["Wearable", "Server", "Router", "Gateway"], "options_hi": ["पहनने योग्य", "सर्वर", "राउटर", "गेटवे"],
     "a": 0, "exp_en": "Smart watches are wearable IoT devices.", "exp_hi": "स्मार्ट वॉच पहनने योग्य IoT उपकरण है।"},
    {"q_en": "Which sensor measures temperature and humidity?", "q_hi": "तापमान और आर्द्रता कौन-सा सेंसर मापता है?",
     "options_en": ["LDR", "DHT11", "PIR", "Microphone"], "options_hi": ["LDR", "DHT11", "PIR", "माइक्रोफोन"],
     "a": 1, "exp_en": "DHT11 measures temperature and humidity.", "exp_hi": "DHT11 तापमान और आर्द्रता मापता है।"},
    {"q_en": "What is a major IoT security concern?", "q_hi": "IoT सुरक्षा की मुख्य चिंता क्या है?",
     "options_en": ["Speed", "Data privacy and breaches", "Color", "Weight"], "options_hi": ["गति", "डेटा गोपनीयता और सेंध", "रंग", "वज़न"],
     "a": 1, "exp_en": "Protecting data and preventing breaches is key.", "exp_hi": "डेटा की सुरक्षा मुख्य चिंता है।"},
    {"q_en": "Which is a short-range IoT protocol?", "q_hi": "कम दूरी का IoT प्रोटोकॉल कौन-सा है?",
     "options_en": ["LoRa", "NB-IoT", "Zigbee", "Cellular"], "options_hi": ["LoRa", "NB-IoT", "ज़िगबी", "सेलुलर"],
     "a": 2, "exp_en": "Zigbee is a short-range low-power protocol.", "exp_hi": "ज़िगबी कम दूरी का कम बिजली वाला प्रोटोकॉल है।"},
    {"q_en": "How is IoT used in smart agriculture?", "q_hi": "स्मार्ट कृषि में IoT का उपयोग कैसे होता है?",
     "options_en": ["Monitor soil moisture", "Play music", "Print books", "None"], "options_hi": ["मिट्टी की नमी मॉनिटर करना", "संगीत चलाना", "किताबें छापना", "कोई नहीं"],
     "a": 0, "exp_en": "Sensors monitor soil moisture, temperature, weather etc.", "exp_hi": "सेंसर मिट्टी की नमी, तापमान आदि मॉनिटर करते हैं।"},
    {"q_en": "What are the 3V's of Big Data?", "q_hi": "बिग डेटा के तीन V क्या हैं?",
     "options_en": ["Volume, Velocity, Variety", "Value, View, Verify", "Vector, Volt, Vast", "None"], "options_hi": ["वॉल्यूम, वेलोसिटी, वेरायटी", "वैल्यू, व्यू, वेरीफाई", "वेक्टर, वोल्ट, वास्ट", "कोई नहीं"],
     "a": 0, "exp_en": "The 3Vs are Volume, Velocity, Variety.", "exp_hi": "तीन V हैं वॉल्यूम, वेलोसिटी, वेरायटी।"},
    {"q_en": "What does an IoT gateway do?", "q_hi": "IoT गेटवे का कार्य क्या है?",
     "options_en": ["Powers sensors", "Bridges devices and cloud", "Stores data", "Cools the system"], "options_hi": ["सेंसर को बिजली देना", "उपकरणों और क्लाउड को जोड़ना", "डेटा संग्रह करना", "प्रणाली ठंडी करना"],
     "a": 1, "exp_en": "Gateway connects local devices to the cloud.", "exp_hi": "गेटवे स्थानीय उपकरणों को क्लाउड से जोड़ता है।"},
    {"q_en": "What does a PIR sensor detect?", "q_hi": "PIR सेंसर क्या पहचानता है?",
     "options_en": ["Temperature", "Motion", "Pressure", "Humidity"], "options_hi": ["तापमान", "गति", "दबाव", "आर्द्रता"],
     "a": 1, "exp_en": "PIR (Passive Infrared) detects motion.", "exp_hi": "PIR सेंसर गति का पता लगाता है।"},
    {"q_en": "Which platform helps visualize IoT data?", "q_hi": "IoT डेटा दिखाने में कौन-सा प्लेटफ़ॉर्म मदद करता है?",
     "options_en": ["ThingSpeak", "Photoshop", "MS Paint", "Notepad"], "options_hi": ["ThingSpeak", "फोटोशॉप", "MS पेंट", "नोटपैड"],
     "a": 0, "exp_en": "ThingSpeak is an IoT analytics cloud platform.", "exp_hi": "ThingSpeak IoT एनालिटिक्स का क्लाउड मंच है।"},
    {"q_en": "What does M2M stand for?", "q_hi": "M2M का पूर्ण रूप क्या है?",
     "options_en": ["Machine to Machine", "Man to Man", "Memory to Memory", "Module to Module"], "options_hi": ["मशीन टू मशीन", "मैन टू मैन", "मेमोरी टू मेमोरी", "मॉड्यूल टू मॉड्यूल"],
     "a": 0, "exp_en": "M2M = Machine to Machine communication.", "exp_hi": "M2M यानी मशीन से मशीन संचार।"},
    {"q_en": "Which language is commonly used with Arduino?", "q_hi": "Arduino के साथ आमतौर पर कौन-सी भाषा प्रयोग होती है?",
     "options_en": ["Python", "C/C++", "Java", "Ruby"], "options_hi": ["पायथन", "C/C++", "जावा", "रूबी"],
     "a": 1, "exp_en": "Arduino IDE uses C/C++ based language.", "exp_hi": "Arduino IDE C/C++ आधारित भाषा प्रयोग करती है।"},
    {"q_en": "What is edge computing?", "q_hi": "एज कंप्यूटिंग क्या है?",
     "options_en": ["Processing at source", "Only cloud processing", "No processing", "Only storage"], "options_hi": ["स्रोत पर प्रसंस्करण", "केवल क्लाउड प्रसंस्करण", "कोई प्रसंस्करण नहीं", "केवल संग्रहण"],
     "a": 0, "exp_en": "Edge computing processes data near the source rather than in the cloud.", "exp_hi": "एज कंप्यूटिंग डेटा को स्रोत के पास ही प्रोसेस करती है।"},
    {"q_en": "Which component converts analog signals to digital?", "q_hi": "एनालॉग संकेत को डिजिटल में कौन बदलता है?",
     "options_en": ["DAC", "ADC", "Amplifier", "Resistor"], "options_hi": ["DAC", "ADC", "एम्प्लिफ़ायर", "रेसिस्टर"],
     "a": 1, "exp_en": "ADC = Analog to Digital Converter.", "exp_hi": "ADC एनालॉग को डिजिटल में बदलता है।"},
    {"q_en": "What does LDR stand for?", "q_hi": "LDR का पूर्ण रूप क्या है?",
     "options_en": ["Light Dependent Resistor", "Low Duty Resistor", "Linear Digital Relay", "Long Distance Radar"], "options_hi": ["लाइट डिपेंडेंट रेसिस्टर", "लो ड्यूटी रेसिस्टर", "लीनियर डिजिटल रिले", "लॉन्ग डिस्टेंस रडार"],
     "a": 0, "exp_en": "LDR is a light-dependent resistor.", "exp_hi": "LDR प्रकाश पर निर्भर प्रतिरोधक है।"},
    {"q_en": "Which device controls multiple IoT things at home?", "q_hi": "घर के अनेक IoT उपकरण कौन नियंत्रित करता है?",
     "options_en": ["Smart Hub", "Fan Regulator", "Mixer", "TV Antenna"], "options_hi": ["स्मार्ट हब", "पंखे का रेगुलेटर", "मिक्सर", "टीवी एंटेना"],
     "a": 0, "exp_en": "Smart Hubs (e.g. Google Nest) centrally control IoT devices.", "exp_hi": "स्मार्ट हब IoT उपकरणों को केंद्रीय रूप से नियंत्रित करता है।"},
    {"q_en": "A typical IoT device uses which kind of network?", "q_hi": "सामान्य IoT उपकरण किस प्रकार का नेटवर्क उपयोग करता है?",
     "options_en": ["Only wired", "Only mobile", "Both wired and wireless", "No network"], "options_hi": ["केवल तारयुक्त", "केवल मोबाइल", "तारयुक्त और वायरलेस दोनों", "कोई नेटवर्क नहीं"],
     "a": 2, "exp_en": "IoT devices can use wired or wireless networks.", "exp_hi": "IoT उपकरण तारयुक्त या वायरलेस दोनों नेटवर्क प्रयोग कर सकते हैं।"},
    {"q_en": "Which is NOT a common IoT application?", "q_hi": "इनमें से कौन सामान्य IoT अनुप्रयोग नहीं है?",
     "options_en": ["Smart city", "Smart health", "Smart farming", "Paper printing"], "options_hi": ["स्मार्ट सिटी", "स्मार्ट स्वास्थ्य", "स्मार्ट कृषि", "कागज़ मुद्रण"],
     "a": 3, "exp_en": "Paper printing is not a primary IoT area.", "exp_hi": "कागज़ मुद्रण मुख्य IoT क्षेत्र नहीं है।"},
    {"q_en": "Which standard is widely used for connecting IoT devices in home networks?", "q_hi": "घरेलू IoT नेटवर्क में सबसे ज़्यादा कौन-सा मानक प्रयोग होता है?",
     "options_en": ["Wi-Fi", "Ethernet only", "VSAT", "PSTN"], "options_hi": ["वाई-फाई", "केवल ईथरनेट", "VSAT", "PSTN"],
     "a": 0, "exp_en": "Wi-Fi is common for home IoT connectivity.", "exp_hi": "घरेलू IoT में वाई-फाई सबसे प्रचलित है।"},
    {"q_en": "What is 'smart city'?", "q_hi": "स्मार्ट सिटी क्या है?",
     "options_en": ["City with no cars", "City using IoT and data for better services", "City on hills", "Traditional village"], "options_hi": ["बिना कार वाला शहर", "IoT और डेटा से बेहतर सेवाओं वाला शहर", "पहाड़ी शहर", "पारंपरिक गाँव"],
     "a": 1, "exp_en": "Smart cities use IoT/data to improve services.", "exp_hi": "स्मार्ट सिटी IoT और डेटा से सेवाओं में सुधार करती है।"},
    {"q_en": "Which IoT-capable ship/vehicle tracker uses GPS?", "q_hi": "GPS आधारित कौन-सा IoT ट्रैकर है?",
     "options_en": ["Logistics tracker", "Calculator", "Microwave", "CD player"], "options_hi": ["लॉजिस्टिक ट्रैकर", "कैलकुलेटर", "माइक्रोवेव", "सीडी प्लेयर"],
     "a": 0, "exp_en": "Logistics/fleet trackers use GPS with IoT.", "exp_hi": "लॉजिस्टिक ट्रैकर GPS IoT का प्रयोग करते हैं।"},
    {"q_en": "Which open-source IoT platform is widely used?", "q_hi": "कौन-सा ओपन-सोर्स IoT प्लेटफ़ॉर्म प्रचलित है?",
     "options_en": ["ThingsBoard", "Adobe Reader", "VLC", "WinZip"], "options_hi": ["थिंग्सबोर्ड", "एडोब रीडर", "वीएलसी", "विनज़िप"],
     "a": 0, "exp_en": "ThingsBoard is a popular open-source IoT platform.", "exp_hi": "थिंग्सबोर्ड एक लोकप्रिय ओपन-सोर्स IoT मंच है।"},
    {"q_en": "Which pin type on Arduino gives varying analog-like output via PWM?", "q_hi": "Arduino पर PWM द्वारा एनालॉग-जैसा आउटपुट देने वाला पिन कौन-सा है?",
     "options_en": ["Analog Input", "PWM digital pin", "Ground", "VIN"], "options_hi": ["एनालॉग इनपुट", "PWM डिजिटल पिन", "ग्राउंड", "VIN"],
     "a": 1, "exp_en": "PWM pins (~) simulate analog output.", "exp_hi": "PWM पिन (~) एनालॉग-जैसा आउटपुट देते हैं।"},
    {"q_en": "Which is NOT a common IoT communication protocol?", "q_hi": "इनमें से कौन सामान्य IoT संचार प्रोटोकॉल नहीं है?",
     "options_en": ["MQTT", "CoAP", "HTTP", "JPEG"], "options_hi": ["MQTT", "CoAP", "HTTP", "JPEG"],
     "a": 3, "exp_en": "JPEG is an image format, not a protocol.", "exp_hi": "JPEG चित्र प्रारूप है, प्रोटोकॉल नहीं।"},
    {"q_en": "IoT devices often run on?", "q_hi": "IoT उपकरण अक्सर किस पर चलते हैं?",
     "options_en": ["Mainframes", "Embedded firmware", "Full Windows", "Paper"], "options_hi": ["मेनफ्रेम", "एम्बेडेड फर्मवेयर", "पूर्ण विंडोज़", "कागज़"],
     "a": 1, "exp_en": "IoT devices run on embedded firmware.", "exp_hi": "IoT उपकरण एम्बेडेड फर्मवेयर पर चलते हैं।"},
    {"q_en": "Which is an example of a wearable health IoT device?", "q_hi": "पहनने योग्य स्वास्थ्य IoT उपकरण का उदाहरण कौन-सा है?",
     "options_en": ["Fitness band", "Ceiling fan", "Oven", "Projector"], "options_hi": ["फिटनेस बैंड", "पंखा", "ओवन", "प्रोजेक्टर"],
     "a": 0, "exp_en": "Fitness bands track health metrics and are wearable IoT.", "exp_hi": "फिटनेस बैंड पहनने योग्य IoT स्वास्थ्य उपकरण है।"},
    {"q_en": "Which is a benefit of IoT?", "q_hi": "IoT का एक लाभ कौन-सा है?",
     "options_en": ["Remote monitoring", "More paperwork", "Slower response", "Higher downtime"], "options_hi": ["दूर से निगरानी", "अधिक कागज़ी कार्य", "धीमा प्रतिसाद", "अधिक बंद रहना"],
     "a": 0, "exp_en": "IoT enables remote real-time monitoring.", "exp_hi": "IoT दूर से रीयल-टाइम निगरानी देता है।"},
    {"q_en": "What is 'smart metering'?", "q_hi": "'स्मार्ट मीटरिंग' क्या है?",
     "options_en": ["Measuring speed", "Digital meters that send usage data", "Manual billing", "Paper meters"], "options_hi": ["गति मापना", "डिजिटल मीटर जो उपयोग डेटा भेजते हैं", "मैनुअल बिलिंग", "कागज़ी मीटर"],
     "a": 1, "exp_en": "Smart meters auto-report consumption data.", "exp_hi": "स्मार्ट मीटर उपयोग डेटा स्वतः भेजते हैं।"},
    {"q_en": "Which protocol is used for short web-like IoT requests?", "q_hi": "छोटे वेब-जैसे IoT अनुरोधों के लिए प्रोटोकॉल कौन-सा है?",
     "options_en": ["CoAP", "SSH", "Telnet", "SMTP"], "options_hi": ["CoAP", "SSH", "Telnet", "SMTP"],
     "a": 0, "exp_en": "CoAP is a lightweight HTTP-like protocol for constrained IoT devices.", "exp_hi": "CoAP सीमित उपकरणों के लिए हल्का HTTP-जैसा प्रोटोकॉल है।"},
    {"q_en": "A major challenge in IoT is?", "q_hi": "IoT में एक बड़ी चुनौती क्या है?",
     "options_en": ["Interoperability", "Too few devices", "Excessive power", "No internet"], "options_hi": ["इंटरऑपरेबिलिटी", "बहुत कम उपकरण", "अत्यधिक ऊर्जा", "कोई इंटरनेट नहीं"],
     "a": 0, "exp_en": "Different IoT devices/standards must work together (interoperability).", "exp_hi": "विभिन्न IoT मानकों के बीच तालमेल चुनौती है।"},
    {"q_en": "Which architecture is typical for IoT apps?", "q_hi": "IoT अनुप्रयोग की सामान्य संरचना कौन-सी है?",
     "options_en": ["Monolithic desktop", "Client-server/cloud based", "Purely offline", "None"], "options_hi": ["मोनोलिथिक डेस्कटॉप", "क्लाइंट-सर्वर/क्लाउड आधारित", "पूरी तरह ऑफ़लाइन", "कोई नहीं"],
     "a": 1, "exp_en": "IoT uses client-server / cloud architecture.", "exp_hi": "IoT अनुप्रयोग क्लाइंट-सर्वर/क्लाउड संरचना पर आधारित हैं।"},
    {"q_en": "Which sensor detects gas like LPG?", "q_hi": "कौन-सा सेंसर LPG जैसी गैस पहचानता है?",
     "options_en": ["MQ-2", "DHT22", "HC-SR04", "Soil Moisture"], "options_hi": ["MQ-2", "DHT22", "HC-SR04", "सॉइल मॉइस्चर"],
     "a": 0, "exp_en": "MQ-2 detects smoke and combustible gases.", "exp_hi": "MQ-2 धुआँ और ज्वलनशील गैस पहचानता है।"},
    {"q_en": "HC-SR04 is used to measure?", "q_hi": "HC-SR04 किसे मापता है?",
     "options_en": ["Distance (ultrasonic)", "Humidity", "Light", "Voltage"], "options_hi": ["दूरी (अल्ट्रासॉनिक)", "आर्द्रता", "प्रकाश", "वोल्टेज"],
     "a": 0, "exp_en": "HC-SR04 is an ultrasonic distance sensor.", "exp_hi": "HC-SR04 अल्ट्रासॉनिक दूरी सेंसर है।"},
    {"q_en": "In IoT, 'firmware' is?", "q_hi": "IoT में 'फर्मवेयर' क्या है?",
     "options_en": ["Plastic casing", "Software permanently stored on device", "Wall power", "Optional"], "options_hi": ["प्लास्टिक का आवरण", "उपकरण पर स्थायी रूप से संग्रहीत सॉफ्टवेयर", "दीवार की बिजली", "वैकल्पिक"],
     "a": 1, "exp_en": "Firmware runs on the device, permanent low-level software.", "exp_hi": "फर्मवेयर उपकरण पर स्थायी लो-लेवल सॉफ्टवेयर है।"},
    {"q_en": "Which is a real-time IoT communication protocol?", "q_hi": "रीयल-टाइम IoT संचार का प्रोटोकॉल कौन-सा है?",
     "options_en": ["MQTT", "IMAP", "POP3", "DHCP"], "options_hi": ["MQTT", "IMAP", "POP3", "DHCP"],
     "a": 0, "exp_en": "MQTT supports real-time pub/sub messaging.", "exp_hi": "MQTT रीयल-टाइम पब/सब मैसेजिंग देता है।"},
    {"q_en": "Which cloud service offers IoT backend at scale?", "q_hi": "बड़े स्तर पर IoT बैकएंड कौन-सी क्लाउड सेवा देती है?",
     "options_en": ["AWS IoT", "MS Word", "Photoshop", "VLC"], "options_hi": ["AWS IoT", "MS वर्ड", "फ़ोटोशॉप", "वीएलसी"],
     "a": 0, "exp_en": "AWS IoT Core offers scalable IoT backend services.", "exp_hi": "AWS IoT Core बड़े स्तर पर IoT बैकएंड देता है।"},
]

ALL_QUESTIONS = {"M1": M1, "M2": M2, "M3": M3, "M4": M4}

# Extend with extras (50 more per subject) → total 100 per subject
try:
    from extras_m1 import M1_EXTRA
    from extras_m2 import M2_EXTRA
    from extras_m3 import M3_EXTRA
    from extras_m4 import M4_EXTRA
    ALL_QUESTIONS = {
        "M1": M1 + M1_EXTRA,
        "M2": M2 + M2_EXTRA,
        "M3": M3 + M3_EXTRA,
        "M4": M4 + M4_EXTRA,
    }
except ImportError:
    pass

# Top-up to guarantee 100+ per subject
try:
    from extras_topup import TOPUP
    for _code, _items in TOPUP.items():
        if _code in ALL_QUESTIONS:
            ALL_QUESTIONS[_code] = ALL_QUESTIONS[_code] + _items
except ImportError:
    pass
