"""Seed question bank for O Level exam prep - Hinglish friendly."""

QUESTIONS = {
    "M1": [
        {"q": "Computer ka full form kya hai? / What is the full form of COMPUTER?", "options": ["Common Operating Machine Purposely Used for Technological and Educational Research", "Common Object Machine Used in Technical Electronic Research", "Central Operating Machine Purpose Used for Tech Education Research", "None of these"], "a": 0, "exp": "COMPUTER stands for Common Operating Machine Purposely Used for Technological and Educational Research."},
        {"q": "Which of the following is an input device?", "options": ["Monitor", "Keyboard", "Printer", "Speaker"], "a": 1, "exp": "Keyboard is used to input data; monitor/printer/speakers are output devices."},
        {"q": "1 KB is equal to how many bytes?", "options": ["1000", "1024", "100", "512"], "a": 1, "exp": "1 KB = 1024 bytes in binary."},
        {"q": "Which is volatile memory?", "options": ["ROM", "Hard Disk", "RAM", "Flash Drive"], "a": 2, "exp": "RAM (Random Access Memory) is volatile - data is lost on power off."},
        {"q": "MS Word mein file ka default extension kya hota hai (MS Office 2010+)?", "options": [".doc", ".docx", ".txt", ".pdf"], "a": 1, "exp": "From MS Office 2007 onwards, Word uses .docx as default extension."},
        {"q": "Ctrl + C shortcut is used for?", "options": ["Cut", "Copy", "Paste", "Close"], "a": 1, "exp": "Ctrl+C copies selected content to clipboard."},
        {"q": "Which device is used to connect a computer to the internet?", "options": ["Router", "Modem", "Switch", "Hub"], "a": 1, "exp": "Modem modulates/demodulates signals to connect to ISP."},
        {"q": "Operating System ka primary function kya hai?", "options": ["Manage hardware and software resources", "Edit documents", "Browse internet", "Play music"], "a": 0, "exp": "OS manages all hardware and software resources of a computer."},
        {"q": "Which of these is NOT an operating system?", "options": ["Windows", "Linux", "Oracle", "macOS"], "a": 2, "exp": "Oracle is a database management system, not an OS."},
        {"q": "Binary system uses which digits?", "options": ["0-9", "0 and 1", "0-7", "A-F"], "a": 1, "exp": "Binary number system uses only 0 and 1."},
        {"q": "CPU ka full form?", "options": ["Central Processing Unit", "Computer Personal Unit", "Central Process Utility", "Control Program Unit"], "a": 0, "exp": "CPU = Central Processing Unit - brain of computer."},
        {"q": "Which key is used to delete the character to the left of cursor?", "options": ["Delete", "Backspace", "Shift", "Enter"], "a": 1, "exp": "Backspace deletes character to the left of cursor."},
        {"q": "Ek byte mein kitne bits hote hain?", "options": ["4", "8", "16", "32"], "a": 1, "exp": "1 byte = 8 bits."},
        {"q": "Which is a system software?", "options": ["MS Word", "Photoshop", "Windows 10", "VLC Player"], "a": 2, "exp": "Windows 10 is a system software (Operating System)."},
        {"q": "Excel file ka extension kya hota hai?", "options": [".xls/.xlsx", ".doc", ".ppt", ".txt"], "a": 0, "exp": "Excel files use .xls or .xlsx extension."},
        {"q": "World Wide Web ke inventor kaun hain?", "options": ["Bill Gates", "Tim Berners-Lee", "Steve Jobs", "Larry Page"], "a": 1, "exp": "Tim Berners-Lee invented the WWW in 1989."},
        {"q": "Which key combination refreshes a webpage?", "options": ["Ctrl+R / F5", "Ctrl+F", "Alt+F4", "Ctrl+Z"], "a": 0, "exp": "F5 or Ctrl+R refreshes the current webpage."},
        {"q": "HTTPS mein 'S' ka matlab?", "options": ["Simple", "Secure", "Strong", "Smart"], "a": 1, "exp": "HTTPS = HyperText Transfer Protocol Secure."},
        {"q": "Which of these stores data permanently?", "options": ["RAM", "Cache", "Hard Disk", "Register"], "a": 2, "exp": "Hard Disk is non-volatile and stores data permanently."},
        {"q": "GUI ka full form?", "options": ["Graphic User Interface", "Graphical User Interface", "General User Interface", "Geographical Unit Interface"], "a": 1, "exp": "GUI = Graphical User Interface."},
        {"q": "Which tab in MS Word contains the 'Font' group?", "options": ["Home", "Insert", "Review", "View"], "a": 0, "exp": "Home tab contains Font formatting options."},
        {"q": "Computer network mein LAN ka full form?", "options": ["Local Area Network", "Large Area Network", "Link Access Network", "Long Area Network"], "a": 0, "exp": "LAN = Local Area Network."},
        {"q": "Which printer is faster and quieter?", "options": ["Dot Matrix", "Laser", "Inkjet", "Daisy Wheel"], "a": 1, "exp": "Laser printers are fast, quiet and high-quality."},
        {"q": "Cloud computing ka example?", "options": ["Notepad", "Google Drive", "MS Paint", "Calculator"], "a": 1, "exp": "Google Drive is a cloud storage service."},
        {"q": "Antivirus ka kaam?", "options": ["Create virus", "Detect and remove malware", "Speed up internet", "Edit photos"], "a": 1, "exp": "Antivirus detects and removes viruses/malware."}
    ],
    "M2": [
        {"q": "HTML ka full form kya hai?", "options": ["Hyper Text Markup Language", "High Text Machine Language", "Hyper Tabular Markup Language", "None"], "a": 0, "exp": "HTML = HyperText Markup Language."},
        {"q": "Which tag creates the largest heading in HTML?", "options": ["<h6>", "<h1>", "<head>", "<heading>"], "a": 1, "exp": "<h1> is the largest heading; <h6> is smallest."},
        {"q": "CSS ka full form?", "options": ["Cascading Style Sheets", "Computer Style Sheets", "Creative Style System", "Colorful Style Sheets"], "a": 0, "exp": "CSS = Cascading Style Sheets."},
        {"q": "Which tag is used to insert an image in HTML?", "options": ["<img>", "<image>", "<pic>", "<src>"], "a": 0, "exp": "<img> tag is used with src attribute to insert images."},
        {"q": "Hyperlink banane ke liye kaun sa tag use hota hai?", "options": ["<link>", "<a>", "<href>", "<url>"], "a": 1, "exp": "Anchor tag <a> with href attribute creates hyperlinks."},
        {"q": "Which CSS property changes text color?", "options": ["font-color", "text-color", "color", "foreground"], "a": 2, "exp": "'color' property sets the text color in CSS."},
        {"q": "HTML5 mein video embed karne ke liye?", "options": ["<video>", "<media>", "<movie>", "<play>"], "a": 0, "exp": "<video> tag is new in HTML5 for embedding video."},
        {"q": "Which attribute specifies an alternate text for an image?", "options": ["title", "alt", "src", "longdesc"], "a": 1, "exp": "'alt' provides alternate text if image fails to load."},
        {"q": "JavaScript mainly used for?", "options": ["Styling pages", "Structuring pages", "Client-side interactivity", "Database management"], "a": 2, "exp": "JavaScript is mainly used for client-side interactivity."},
        {"q": "Which tag is used for unordered list?", "options": ["<ol>", "<ul>", "<li>", "<list>"], "a": 1, "exp": "<ul> creates unordered (bulleted) list."},
        {"q": "CSS mein class selector ka symbol?", "options": ["#", ".", "*", "@"], "a": 1, "exp": "Class selector uses a dot (.) prefix."},
        {"q": "ID selector ka symbol?", "options": ["#", ".", "&", "$"], "a": 0, "exp": "ID selector uses hash (#) prefix."},
        {"q": "Which HTML element defines the document title?", "options": ["<meta>", "<head>", "<title>", "<h1>"], "a": 2, "exp": "<title> defines the browser tab / document title."},
        {"q": "<br> tag ka kaam?", "options": ["Bold text", "Line break", "Border remove", "Background"], "a": 1, "exp": "<br> inserts a single line break."},
        {"q": "Which is correct DOCTYPE for HTML5?", "options": ["<!DOCTYPE html5>", "<!DOCTYPE html>", "<DOCTYPE HTML>", "<!HTML5>"], "a": 1, "exp": "HTML5 uses simple <!DOCTYPE html>."},
        {"q": "Inline CSS applied using which attribute?", "options": ["class", "id", "style", "css"], "a": 2, "exp": "style attribute applies inline CSS."},
        {"q": "Which property sets background color in CSS?", "options": ["bgcolor", "background-color", "color-bg", "back-color"], "a": 1, "exp": "'background-color' sets the background."},
        {"q": "HTML form submit karne ke liye button type?", "options": ["send", "submit", "form-send", "post"], "a": 1, "exp": "type=\"submit\" submits the form."},
        {"q": "Table row ka tag?", "options": ["<td>", "<tr>", "<th>", "<row>"], "a": 1, "exp": "<tr> = table row; <td> = table data."},
        {"q": "Which CSS property controls element spacing inside border?", "options": ["margin", "padding", "spacing", "border-space"], "a": 1, "exp": "Padding is space inside border; margin is outside."},
        {"q": "Semantic tag for navigation?", "options": ["<nav>", "<div>", "<menu>", "<links>"], "a": 0, "exp": "<nav> is the HTML5 semantic tag for navigation."},
        {"q": "Which color code is red?", "options": ["#00FF00", "#FF0000", "#0000FF", "#FFFF00"], "a": 1, "exp": "#FF0000 is pure red in hex."},
        {"q": "Responsive design ka matlab?", "options": ["Fast loading", "Adapts to screen size", "High quality graphics", "Good animations"], "a": 1, "exp": "Responsive design adapts layout to different screen sizes."},
        {"q": "Meta viewport tag ka use?", "options": ["SEO", "Responsive scaling on mobile", "Security", "Styling"], "a": 1, "exp": "Viewport meta tag controls scaling on mobile devices."},
        {"q": "Which tag is used for line break without paragraph?", "options": ["<p>", "<br>", "<hr>", "<lb>"], "a": 1, "exp": "<br> gives line break; <hr> gives horizontal rule."}
    ],
    "M3": [
        {"q": "Python ka creator kaun hai?", "options": ["James Gosling", "Guido van Rossum", "Dennis Ritchie", "Bjarne Stroustrup"], "a": 1, "exp": "Guido van Rossum created Python in 1991."},
        {"q": "Python mein comment likhne ke liye kaun sa symbol use hota hai?", "options": ["//", "#", "/* */", "--"], "a": 1, "exp": "Python uses # for single-line comments."},
        {"q": "Which of these is a mutable data type in Python?", "options": ["tuple", "string", "list", "int"], "a": 2, "exp": "List is mutable; tuple, string, int are immutable."},
        {"q": "Output of print(2 ** 3)?", "options": ["6", "8", "9", "5"], "a": 1, "exp": "** is power operator; 2^3 = 8."},
        {"q": "Which keyword defines a function in Python?", "options": ["function", "def", "fun", "define"], "a": 1, "exp": "'def' keyword is used to define functions."},
        {"q": "Python mein list ka index kahan se start hota hai?", "options": ["0", "1", "-1", "Depends"], "a": 0, "exp": "Python list indices start from 0."},
        {"q": "Which operator is used for integer division?", "options": ["/", "//", "%", "**"], "a": 1, "exp": "// is integer (floor) division."},
        {"q": "Output of len(\"Python\")?", "options": ["5", "6", "7", "Error"], "a": 1, "exp": "The string 'Python' has 6 characters."},
        {"q": "Which function takes user input?", "options": ["scan()", "read()", "input()", "get()"], "a": 2, "exp": "input() reads a string from user."},
        {"q": "Python file extension?", "options": [".pyt", ".py", ".python", ".p"], "a": 1, "exp": "Python files use .py extension."},
        {"q": "Tuple kaise create karte hain?", "options": ["[1,2,3]", "(1,2,3)", "{1,2,3}", "<1,2,3>"], "a": 1, "exp": "Tuples are created using parentheses ()."},
        {"q": "Dictionary syntax?", "options": ["{key: value}", "[key: value]", "(key: value)", "<key=value>"], "a": 0, "exp": "Dictionaries use curly braces with key:value pairs."},
        {"q": "Which statement handles exceptions?", "options": ["try-except", "if-else", "do-while", "catch-throw"], "a": 0, "exp": "try-except is Python's exception handling."},
        {"q": "Boolean values in Python?", "options": ["true/false", "True/False", "TRUE/FALSE", "1/0 only"], "a": 1, "exp": "Python uses True and False (capitalized)."},
        {"q": "range(5) generates?", "options": ["1 to 5", "0 to 5", "0 to 4", "1 to 4"], "a": 2, "exp": "range(5) gives 0,1,2,3,4 (5 numbers)."},
        {"q": "Which is NOT a Python keyword?", "options": ["class", "object", "def", "return"], "a": 1, "exp": "'object' is a built-in class, not a keyword."},
        {"q": "Multi-line string kaise banate hain?", "options": ["\"text\"", "'text'", "\"\"\"text\"\"\"", "<<text>>"], "a": 2, "exp": "Triple quotes \"\"\" or ''' create multi-line strings."},
        {"q": "Output of print(10 % 3)?", "options": ["1", "3", "0", "3.33"], "a": 0, "exp": "% is modulo; 10%3 = 1."},
        {"q": "Which module is used for mathematical operations?", "options": ["math", "maths", "numeric", "calc"], "a": 0, "exp": "import math provides math functions."},
        {"q": "Python is what kind of language?", "options": ["Compiled", "Interpreted", "Assembly", "Machine code"], "a": 1, "exp": "Python is an interpreted, dynamically-typed language."},
        {"q": "Which loop runs at least once?", "options": ["for", "while", "do-while", "None in Python"], "a": 3, "exp": "Python doesn't have do-while; for/while may not run if condition false."},
        {"q": "list.append(x) ka kaam?", "options": ["Adds x at start", "Adds x at end", "Removes x", "Sorts list"], "a": 1, "exp": "append() adds element at end of the list."},
        {"q": "Which method removes last element of list?", "options": ["remove()", "pop()", "delete()", "clear()"], "a": 1, "exp": "pop() removes and returns last element by default."},
        {"q": "Python mein string concatenation ka operator?", "options": ["+", "&", ".", ","], "a": 0, "exp": "+ concatenates strings in Python."},
        {"q": "Which function returns the data type of variable?", "options": ["typeof()", "type()", "datatype()", "class()"], "a": 1, "exp": "type() returns the type of an object."}
    ],
    "M4": [
        {"q": "IoT ka full form?", "options": ["Internet of Things", "Internet of Technology", "Intranet of Things", "Interface of Things"], "a": 0, "exp": "IoT = Internet of Things."},
        {"q": "IoT mein sensor ka main role?", "options": ["Display data", "Collect environmental data", "Store data", "Print data"], "a": 1, "exp": "Sensors collect physical data from the environment."},
        {"q": "Which protocol is commonly used in IoT?", "options": ["MQTT", "FTP", "SMTP", "POP3"], "a": 0, "exp": "MQTT is a lightweight messaging protocol popular for IoT."},
        {"q": "Arduino is a?", "options": ["Operating System", "Microcontroller board", "Database", "Cloud service"], "a": 1, "exp": "Arduino is an open-source microcontroller board."},
        {"q": "Smart home device ka example?", "options": ["Alexa", "Microwave", "Refrigerator (non-smart)", "Fan"], "a": 0, "exp": "Alexa is a smart voice assistant device used in smart homes."},
        {"q": "Which wireless tech has low range and low power (ideal for IoT)?", "options": ["Wi-Fi", "Bluetooth / Zigbee", "4G", "Fiber"], "a": 1, "exp": "Bluetooth/Zigbee offer low-power short-range communication."},
        {"q": "Raspberry Pi kya hai?", "options": ["Fruit", "Single-board computer", "Sensor", "Router"], "a": 1, "exp": "Raspberry Pi is a low-cost single-board computer."},
        {"q": "Actuator ka kaam?", "options": ["Sense environment", "Perform physical action", "Send email", "Store data"], "a": 1, "exp": "Actuators perform actions (motors, valves, switches)."},
        {"q": "Which is NOT an IoT layer?", "options": ["Perception", "Network", "Application", "Compilation"], "a": 3, "exp": "IoT has perception, network, and application layers."},
        {"q": "Cloud computing in IoT is used for?", "options": ["Nothing", "Data storage and processing", "Power supply", "Cooling"], "a": 1, "exp": "Cloud stores and processes massive IoT data."},
        {"q": "RFID ka full form?", "options": ["Radio Frequency Identification", "Random Frequency Interface Device", "Remote Frequency Input Device", "None"], "a": 0, "exp": "RFID = Radio Frequency Identification."},
        {"q": "Which company makes Arduino?", "options": ["Google", "Microsoft", "Arduino LLC", "Intel"], "a": 2, "exp": "Arduino LLC / Arduino.cc develops Arduino boards."},
        {"q": "Sensor data usually analog or digital?", "options": ["Only digital", "Only analog", "Both possible", "Neither"], "a": 2, "exp": "Sensors can produce both analog and digital signals."},
        {"q": "Smart watch is an example of?", "options": ["Wearable IoT", "Server", "Router", "Gateway"], "a": 0, "exp": "Smart watch is a wearable IoT device."},
        {"q": "Which is a temperature sensor?", "options": ["LDR", "DHT11", "PIR", "Microphone"], "a": 1, "exp": "DHT11 measures temperature and humidity."},
        {"q": "IoT security ka main concern?", "options": ["Speed", "Data privacy and breaches", "Color", "Weight"], "a": 1, "exp": "IoT security focuses on data privacy and preventing breaches."},
        {"q": "Which is a short-range IoT protocol?", "options": ["LoRa", "NB-IoT", "Zigbee", "Cellular"], "a": 2, "exp": "Zigbee is a short-range, low-power protocol."},
        {"q": "Smart agriculture mein IoT ka use?", "options": ["Monitor soil moisture", "Play music", "Print books", "None"], "a": 0, "exp": "IoT sensors monitor soil, weather, and crop health."},
        {"q": "Big Data ke 3V?", "options": ["Volume, Velocity, Variety", "Value, View, Verify", "Vector, Volt, Vast", "None"], "a": 0, "exp": "Big Data characterized by Volume, Velocity, Variety."},
        {"q": "Gateway in IoT ka kaam?", "options": ["Power sensors", "Bridge between devices and cloud", "Store data", "Cool the system"], "a": 1, "exp": "IoT Gateway bridges local devices to cloud."},
        {"q": "PIR sensor detects?", "options": ["Temperature", "Motion", "Pressure", "Humidity"], "a": 1, "exp": "PIR (Passive Infrared) sensor detects motion."},
        {"q": "Which platform is commonly used to visualize IoT data?", "options": ["ThingSpeak", "Photoshop", "MS Paint", "Notepad"], "a": 0, "exp": "ThingSpeak is an IoT analytics cloud platform."},
        {"q": "M2M ka full form?", "options": ["Machine to Machine", "Man to Man", "Memory to Memory", "Module to Module"], "a": 0, "exp": "M2M = Machine to Machine communication."},
        {"q": "Which language is commonly used with Arduino?", "options": ["Python", "C/C++", "Java", "Ruby"], "a": 1, "exp": "Arduino IDE uses C/C++ based language."},
        {"q": "Edge computing ka matlab?", "options": ["Processing data at source", "Processing data in cloud only", "No processing", "Only storage"], "a": 0, "exp": "Edge computing processes data near source rather than cloud."}
    ]
}

SUBJECTS = [
    {"code": "M1", "name": "M1 - IT Tools & Business Systems", "color": "m1", "duration_min": 20, "num_questions": 20, "desc": "Fundamentals of computers, MS Office, and internet"},
    {"code": "M2", "name": "M2 - Web Designing & Publishing", "color": "m2", "duration_min": 20, "num_questions": 20, "desc": "HTML, CSS, and web publishing basics"},
    {"code": "M3", "name": "M3 - Programming with Python", "color": "m3", "duration_min": 20, "num_questions": 20, "desc": "Python programming fundamentals"},
    {"code": "M4", "name": "M4 - Internet of Things (IoT)", "color": "m4", "duration_min": 20, "num_questions": 20, "desc": "IoT basics, sensors, and smart devices"},
]

MOCK_TEST = {"code": "MOCK", "name": "Full Mock Test", "duration_min": 60, "num_questions": 50, "desc": "Mix of all 4 subjects - ultimate test!"}
